### ISSUE TITLE
Publication IndexOutOfBoundsException when calling offer() on different threads with random message sizes

### ISSUE THREAD

**Issue by mst4** [real-logic/Aeron#107]
In running the ThwackerTool on Windows, my Publication will spit out IndexOutOfBoundsExceptions when I run with more than one sending thread (sending on the same Publication) using random message sizes.

```
java -cp aeron-tools\build\libs\tools.jar uk.co.real_logic.aeron.tools.ThwackerTool -v yes -d 10000 -e 10 -s 2 --max-size 100 --min-size 64
```

This will cause it to run verifiable streams for 10 seconds with 10 publications, 10 subscriptions, 2 sending threads, and random messages of size 64 to 100 bytes.

It reports multiple of these exceptions:

```
java.lang.IndexOutOfBoundsException: index=65520, length=24, capacity=65536
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:811)
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:740)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendPaddingFrame(LogAppender.java:306)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendUnfragmentedMessage(LogAppender.java:218)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.append(LogAppender.java:144)
	at uk.co.real_logic.aeron.Publication.offer(Publication.java:192)
	at uk.co.real_logic.aeron.tools.ThwackerTool$ThwackingElement.trySendMessage(ThwackerTool.java:884)
	at uk.co.real_logic.aeron.tools.ThwackerTool.sendOnRandomPub(ThwackerTool.java:469)
	at uk.co.real_logic.aeron.tools.ThwackerTool.lambda$createAndStartThreads$14(ThwackerTool.java:299)
	at uk.co.real_logic.aeron.tools.ThwackerTool$$Lambda$63/1068824137.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

It always seems to be at the end of the TermBuffer length dealing with adding padding.  The ThwackerTool uses a TermBuffer length of 65536.  It will only happen with multiple sending threads and random message sizes, as using just one sending thread with random message sizes or 2 sending threads with uniform message size will not cause any issues.

The [ThwackerTool](https://github.com/strangelydim/Aeron/blob/master/aeron-tools/src/main/java/uk/co/real_logic/aeron/tools/ThwackerTool.java)  can be found in the strangelydim fork of Aeron
https://github.com/strangelydim/Aeron
Aeron/aeron-tools/src/main/java/uk/co/real_logic/aeron/tools/ThwackerTool.java

**Comment by mjpt777** [comment]
Can you change the ThwackerTool to catch this exception and get it to report the length it was trying to offer at the time?

**Comment by mst4** [comment]
Here is a portion of the log from a ThwackerTool run.  It reports the stack trace, the offered length when the Exception was caught, and the subsequent error in verifying the stream when the next message comes in after the exception.
```
java.lang.IndexOutOfBoundsException: index=65528, length=24, capacity=65536
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:811)
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:740)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendPaddingFrame(LogAppender.java:306)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendUnfragmentedMessage(LogAppender.java:218)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.append(LogAppender.java:144)
	at uk.co.real_logic.aeron.Publication.offer(Publication.java:192)
	at uk.co.real_logic.aeron.tools.ThwackerTool$ThwackingElement.trySendMessage(ThwackerTool.java:883)
	at uk.co.real_logic.aeron.tools.ThwackerTool.sendOnRandomPub(ThwackerTool.java:470)
	at uk.co.real_logic.aeron.tools.ThwackerTool.lambda$createAndStartThreads$6(ThwackerTool.java:294)
	at uk.co.real_logic.aeron.tools.ThwackerTool$$Lambda$63/1940030785.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
DEBUG Length Offered: 92
WARN Verifiable message stream received sequence number 3488683, but was expecting 3488682. Possibly missed 1 messages. StreamID:9876::SessID:-1131199175::ThreadID:22
java.lang.IndexOutOfBoundsException: index=65520, length=24, capacity=65536
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:811)
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:740)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendPaddingFrame(LogAppender.java:306)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendUnfragmentedMessage(LogAppender.java:218)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.append(LogAppender.java:144)
	at uk.co.real_logic.aeron.Publication.offer(Publication.java:192)
	at uk.co.real_logic.aeron.tools.ThwackerTool$ThwackingElement.trySendMessage(ThwackerTool.java:883)
	at uk.co.real_logic.aeron.tools.ThwackerTool.sendOnRandomPub(ThwackerTool.java:470)
	at uk.co.real_logic.aeron.tools.ThwackerTool.lambda$createAndStartThreads$6(ThwackerTool.java:294)
	at uk.co.real_logic.aeron.tools.ThwackerTool$$Lambda$63/1940030785.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
DEBUG Length Offered: 83
WARN Verifiable message stream received sequence number 3539678, but was expecting 3539677. Possibly missed 1 messages. StreamID:9876::SessID:-1131199175::ThreadID:22
java.lang.IndexOutOfBoundsException: index=65528, length=24, capacity=65536
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:811)
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:740)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendPaddingFrame(LogAppender.java:306)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendUnfragmentedMessage(LogAppender.java:218)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.append(LogAppender.java:144)
	at uk.co.real_logic.aeron.Publication.offer(Publication.java:192)
	at uk.co.real_logic.aeron.tools.ThwackerTool$ThwackingElement.trySendMessage(ThwackerTool.java:883)
	at uk.co.real_logic.aeron.tools.ThwackerTool.sendOnRandomPub(ThwackerTool.java:470)
	at uk.co.real_logic.aeron.tools.ThwackerTool.lambda$createAndStartThreads$6(ThwackerTool.java:294)
	at uk.co.real_logic.aeron.tools.ThwackerTool$$Lambda$63/1940030785.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
DEBUG Length Offered: 97
WARN Verifiable message stream received sequence number 3560305, but was expecting 3560304. Possibly missed 1 messages. StreamID:9876::SessID:-1131199175::ThreadID:22
java.lang.IndexOutOfBoundsException: index=65528, length=24, capacity=65536
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:811)
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:740)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendPaddingFrame(LogAppender.java:306)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendUnfragmentedMessage(LogAppender.java:218)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.append(LogAppender.java:144)
	at uk.co.real_logic.aeron.Publication.offer(Publication.java:192)
	at uk.co.real_logic.aeron.tools.ThwackerTool$ThwackingElement.trySendMessage(ThwackerTool.java:883)
	at uk.co.real_logic.aeron.tools.ThwackerTool.sendOnRandomPub(ThwackerTool.java:470)
	at uk.co.real_logic.aeron.tools.ThwackerTool.lambda$createAndStartThreads$6(ThwackerTool.java:294)
	at uk.co.real_logic.aeron.tools.ThwackerTool$$Lambda$63/1940030785.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
DEBUG Length Offered: 80
WARN Verifiable message stream received sequence number 3565263, but was expecting 3565262. Possibly missed 1 messages. StreamID:9876::SessID:-1131199175::ThreadID:22
java.lang.IndexOutOfBoundsException: index=65528, length=24, capacity=65536
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:811)
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:740)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendPaddingFrame(LogAppender.java:306)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendUnfragmentedMessage(LogAppender.java:218)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.append(LogAppender.java:144)
	at uk.co.real_logic.aeron.Publication.offer(Publication.java:192)
	at uk.co.real_logic.aeron.tools.ThwackerTool$ThwackingElement.trySendMessage(ThwackerTool.java:883)
	at uk.co.real_logic.aeron.tools.ThwackerTool.sendOnRandomPub(ThwackerTool.java:470)
	at uk.co.real_logic.aeron.tools.ThwackerTool.lambda$createAndStartThreads$6(ThwackerTool.java:294)
	at uk.co.real_logic.aeron.tools.ThwackerTool$$Lambda$63/1940030785.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
DEBUG Length Offered: 78
WARN Verifiable message stream received sequence number 3645803, but was expecting 3645802. Possibly missed 1 messages. StreamID:9876::SessID:-1131199175::ThreadID:22
java.lang.IndexOutOfBoundsException: index=65520, length=24, capacity=65536
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:811)
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:740)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendPaddingFrame(LogAppender.java:306)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendUnfragmentedMessage(LogAppender.java:218)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.append(LogAppender.java:144)
	at uk.co.real_logic.aeron.Publication.offer(Publication.java:192)
	at uk.co.real_logic.aeron.tools.ThwackerTool$ThwackingElement.trySendMessage(ThwackerTool.java:883)
	at uk.co.real_logic.aeron.tools.ThwackerTool.sendOnRandomPub(ThwackerTool.java:470)
	at uk.co.real_logic.aeron.tools.ThwackerTool.lambda$createAndStartThreads$6(ThwackerTool.java:294)
	at uk.co.real_logic.aeron.tools.ThwackerTool$$Lambda$63/1940030785.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
DEBUG Length Offered: 89
WARN Verifiable message stream received sequence number 3664445, but was expecting 3664444. Possibly missed 1 messages. StreamID:9876::SessID:-1131199175::ThreadID:22
java.lang.IndexOutOfBoundsException: index=65528, length=24, capacity=65536
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:811)
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:740)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendPaddingFrame(LogAppender.java:306)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendUnfragmentedMessage(LogAppender.java:218)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.append(LogAppender.java:144)
	at uk.co.real_logic.aeron.Publication.offer(Publication.java:192)
	at uk.co.real_logic.aeron.tools.ThwackerTool$ThwackingElement.trySendMessage(ThwackerTool.java:883)
	at uk.co.real_logic.aeron.tools.ThwackerTool.sendOnRandomPub(ThwackerTool.java:470)
	at uk.co.real_logic.aeron.tools.ThwackerTool.lambda$createAndStartThreads$6(ThwackerTool.java:294)
	at uk.co.real_logic.aeron.tools.ThwackerTool$$Lambda$63/1940030785.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
DEBUG Length Offered: 68
WARN Verifiable message stream received sequence number 3707712, but was expecting 3707711. Possibly missed 1 messages. StreamID:9876::SessID:-1131199175::ThreadID:22
java.lang.IndexOutOfBoundsException: index=65528, length=24, capacity=65536
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:811)
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:740)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendPaddingFrame(LogAppender.java:306)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendUnfragmentedMessage(LogAppender.java:218)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.append(LogAppender.java:144)
	at uk.co.real_logic.aeron.Publication.offer(Publication.java:192)
	at uk.co.real_logic.aeron.tools.ThwackerTool$ThwackingElement.trySendMessage(ThwackerTool.java:883)
	at uk.co.real_logic.aeron.tools.ThwackerTool.sendOnRandomPub(ThwackerTool.java:470)
	at uk.co.real_logic.aeron.tools.ThwackerTool.lambda$createAndStartThreads$6(ThwackerTool.java:294)
	at uk.co.real_logic.aeron.tools.ThwackerTool$$Lambda$63/1940030785.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
DEBUG Length Offered: 73
WARN Verifiable message stream received sequence number 3709140, but was expecting 3709139. Possibly missed 1 messages. StreamID:9876::SessID:-1131199175::ThreadID:22
java.lang.IndexOutOfBoundsException: index=65528, length=24, capacity=65536
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:811)
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:740)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendPaddingFrame(LogAppender.java:306)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendUnfragmentedMessage(LogAppender.java:218)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.append(LogAppender.java:144)
	at uk.co.real_logic.aeron.Publication.offer(Publication.java:192)
	at uk.co.real_logic.aeron.tools.ThwackerTool$ThwackingElement.trySendMessage(ThwackerTool.java:883)
	at uk.co.real_logic.aeron.tools.ThwackerTool.sendOnRandomPub(ThwackerTool.java:470)
	at uk.co.real_logic.aeron.tools.ThwackerTool.lambda$createAndStartThreads$6(ThwackerTool.java:294)
	at uk.co.real_logic.aeron.tools.ThwackerTool$$Lambda$63/1940030785.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
DEBUG Length Offered: 89
WARN Verifiable message stream received sequence number 3385996, but was expecting 3385995. Possibly missed 1 messages. StreamID:9876::SessID:-1131199175::ThreadID:21
java.lang.IndexOutOfBoundsException: index=65520, length=24, capacity=65536
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:811)
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:740)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendPaddingFrame(LogAppender.java:306)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendUnfragmentedMessage(LogAppender.java:218)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.append(LogAppender.java:144)
	at uk.co.real_logic.aeron.Publication.offer(Publication.java:192)
	at uk.co.real_logic.aeron.tools.ThwackerTool$ThwackingElement.trySendMessage(ThwackerTool.java:883)
	at uk.co.real_logic.aeron.tools.ThwackerTool.sendOnRandomPub(ThwackerTool.java:470)
	at uk.co.real_logic.aeron.tools.ThwackerTool.lambda$createAndStartThreads$6(ThwackerTool.java:294)
	at uk.co.real_logic.aeron.tools.ThwackerTool$$Lambda$63/1940030785.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
DEBUG Length Offered: 69
WARN Verifiable message stream received sequence number 3723628, but was expecting 3723627. Possibly missed 1 messages. StreamID:9876::SessID:-1131199175::ThreadID:22
java.lang.IndexOutOfBoundsException: index=65528, length=24, capacity=65536
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:811)
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:740)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendPaddingFrame(LogAppender.java:306)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendUnfragmentedMessage(LogAppender.java:218)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.append(LogAppender.java:144)
	at uk.co.real_logic.aeron.Publication.offer(Publication.java:192)
	at uk.co.real_logic.aeron.tools.ThwackerTool$ThwackingElement.trySendMessage(ThwackerTool.java:883)
	at uk.co.real_logic.aeron.tools.ThwackerTool.sendOnRandomPub(ThwackerTool.java:470)
	at uk.co.real_logic.aeron.tools.ThwackerTool.lambda$createAndStartThreads$6(ThwackerTool.java:294)
	at uk.co.real_logic.aeron.tools.ThwackerTool$$Lambda$63/1940030785.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
DEBUG Length Offered: 76
WARN Verifiable message stream received sequence number 3726653, but was expecting 3726652. Possibly missed 1 messages. StreamID:9876::SessID:-1131199175::ThreadID:22
````

**Comment by mjpt777** [comment]
Would one of you guys like to have a go at diagnosing this? @tmontgomery and I are busy getting ready for Chicago in just over a weeks time.

**Comment by strangelydim** [comment]
Here's a simpler test app that reproduces the problem.

Run a driver:

```
java -cp aeron-tools/build/libs/tools.jar uk.co.real_logic.aeron.tools.MediaDriverTool
```

and run a subscriber listening to the publications created in the test app:

```
java -cp aeron-tools/build/libs/tools.jar uk.co.real_logic.aeron.tools.SubscriberTool -c udp://localhost:30123#1
```

And then run this test app:

```
import java.util.concurrent.ThreadLocalRandom;

import uk.co.real_logic.aeron.Aeron;
import uk.co.real_logic.aeron.Aeron.Context;
import uk.co.real_logic.aeron.Publication;
import uk.co.real_logic.aeron.common.concurrent.logbuffer.DataHandler;
import uk.co.real_logic.aeron.common.concurrent.logbuffer.Header;
import uk.co.real_logic.agrona.DirectBuffer;
import uk.co.real_logic.agrona.concurrent.UnsafeBuffer;

public class TwoThreadSendTest implements DataHandler, Runnable
{
    private static final String CHANNEL = "udp://localhost:30123";
    private static final int STREAM_ID = 1;
    private static final int NUM_PUBS = 1;
    private static final int NUM_THREADS = 2;
    private static Publication[] pubs = new Publication[NUM_PUBS];
    private static Thread[] threads = new Thread[NUM_THREADS];

    private static final int NUM_SENDS = 100000000;

    private final int pubIndex;

    public TwoThreadSendTest(final int pubIndex)
    {
        this.pubIndex = pubIndex;
    }

    public static void main(final String[] args)
    {
        final Context ctx = new Aeron.Context();
        final Aeron aeron = Aeron.connect(ctx);

        for (int i = 0; i < NUM_PUBS; i++)
        {
            pubs[i] = aeron.addPublication(CHANNEL, STREAM_ID);
        }

        for (int i = 0; i < NUM_THREADS; i++)
        {
            threads[i] = new Thread(new TwoThreadSendTest(i % NUM_PUBS));
            threads[i].start();
        }

        try
        {
            for (int i = 0; i < NUM_THREADS; i++)
            {
                threads[i].join();
            }
        }
        catch (final InterruptedException e)
        {
            e.printStackTrace();
        }

        for (int i = 0; i < NUM_PUBS; i++)
        {
            pubs[i].close();
        }

        aeron.close();
        ctx.close();
        System.out.println("Done!");
    }

    public void onData(final DirectBuffer buffer, final int offset, final int length,
            final Header header)
    {

    }

    public void run()
    {
        final UnsafeBuffer buf = new UnsafeBuffer(new byte[128]);

        for (int i = 0; i < NUM_SENDS; i++)
        {
            /* Send!  Send!  Send! */
            pubs[pubIndex].offer(buf, 0, ThreadLocalRandom.current().nextInt(100 - 64) + 64);
        }
    }
}
```

And you should get a nice:

```
Exception in thread "Thread-2" java.lang.IndexOutOfBoundsException: index=16777200, length=24, capacity=16777216
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:811)
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:740)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendPaddingFrame(LogAppender.java:303)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendUnfragmentedMessage(LogAppender.java:216)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.append(LogAppender.java:143)
	at uk.co.real_logic.aeron.Publication.offer(Publication.java:192)
	at uk.co.real_logic.aeron.tools.TwoThreadSendTest.run(TwoThreadSendTest.java:82)
	at java.lang.Thread.run(Thread.java:745)
```

spit out.

**Comment by strangelydim** [comment]
So here's what I believe is going on.  You've got two threads, both calling offer on the same publication at the same time.  The term buffer is nearly full; let's say it only has 128 bytes left before the end.

Thread A is trying to write a message that would finish out the term and then require a padding frame.  Let's say it's trying to write a 93 byte message.  So its required aligned frame length is going to be 93 + 24 for the header, rounded to the nearest 4 bytes, so 120.  So after that we'll have only 8 bytes left in the term, which isn't enough for another full 24-byte header, therefore thread A decides that instead of actually writing the message to the buffer, it's going to just write a padding frame and return TRIPPED, allowing the user to try the offer again.  So far, so good...

Thread B, meanwhile, is following the same path, but with a slightly different message size.  Let's say it's trying to write a 99 byte message.  So its aligned frame length is going to be 124.  After thread A already reserved 120 bytes in the term buffer, thread B is left with just 8 bytes remaining, so it too decides it's not going to actually write the message, but instead write a padding frame.

But, you might have noticed, with only 8 bytes left in the buffer, it doesn't actually have enough space even to write a padding frame, which needs 24 bytes.  Unfortunately, that doesn't (currently) prevent it from trying...

If I change this code snippet in `LogAppender:appendUnfragmentedMessage` :
```
        if (isBeyondLogBufferCapacity(frameOffset, alignedLength, capacity))
        {
            if (frameOffset < capacity)
            {
                appendPaddingFrame(termBuffer, frameOffset, capacity);
                return TRIPPED;
            }
            else if (frameOffset == capacity)
            {
                return TRIPPED;
            }

            return FAILED;
        }
```
to this:
```
        if (isBeyondLogBufferCapacity(frameOffset, alignedLength, capacity))
        {
            if ((frameOffset + HEADER_LENGTH) <= capacity)
            {
                appendPaddingFrame(termBuffer, frameOffset, capacity);
                return TRIPPED;
            }
            else if (frameOffset == capacity)
            {
                return TRIPPED;
            }

            return FAILED;
        }
```

to try to account for the header length of the padding frame itself... things seem to work fine.  I assume that if that really does fix things, the same change would need to be made to the same code block in `appendFragmentedMessage` as well.

If my understanding of what's going on is correct, then requiring two different message sizes or random message sizes has nothing to do with it; you can use the same message size for both threads so long as you happen to pick a size that doesn't divide evenly into the term buffer and leaves you with a remainder less than a HEADER_LENGTH.  And, in fact, running a test with both threads sending 64-byte messages (application messages, so 88 bytes aligned with header) also causes the exception.

Now... things can "appear" to work for the wrong reasons, and I don't understand enough about padding frames and alignment at the moment - particularly about how a receiving media driver scanning for new messages is going to behave at the end of a log buffer that has < HEADER_LENGTH worth of padding bytes in it - to be sure that I've fixed anything without introducing more trouble.  But I _believe_ I've at least found the problem.
