### ISSUE TITLE
Creating and deleting subscriptions quickly ruins the driver's day

### ISSUE THREAD

**Issue by strangelydim** [real-logic/Aeron#112]
Start a driver; then run this test:

```
import java.util.concurrent.ThreadLocalRandom;

import uk.co.real_logic.aeron.Aeron;
import uk.co.real_logic.aeron.Aeron.Context;
import uk.co.real_logic.aeron.Subscription;
import uk.co.real_logic.aeron.common.concurrent.logbuffer.DataHandler;
import uk.co.real_logic.aeron.common.concurrent.logbuffer.Header;
import uk.co.real_logic.agrona.DirectBuffer;

public class SubCreateDeleteTest implements DataHandler, Runnable
{
    private static final String CHANNEL = "udp://localhost:30123";
    private static final int NUM_SUBS = 10;

    private static Subscription[] subs = new Subscription[NUM_SUBS];
    private static Object[] locks = new Object[NUM_SUBS];

    private static final int NUM_ITERATIONS = 10000;

    private final Aeron aeron;

    public SubCreateDeleteTest(final Aeron aeron)
    {
        this.aeron = aeron;
    }

    public static void main(final String[] args)
    {
        final Context ctx = new Aeron.Context();
        final Aeron aeron = Aeron.connect(ctx);

        for (int i = 0; i < NUM_SUBS; i++)
        {
            locks[i] = new Object();
        }

        final Thread t1 = new Thread(new SubCreateDeleteTest(aeron));
        final Thread t2 = new Thread(new SubCreateDeleteTest(aeron));

        t1.start();
        t2.start();

        try
        {
            t1.join();
            t2.join();
        }
        catch (final InterruptedException e)
        {
            e.printStackTrace();
        }
        aeron.close();
        ctx.close();
        System.out.println("Done!");
    }

    public void onData(final DirectBuffer buffer, final int offset, final int length,
            final Header header)
    {

    }

    public void run()
    {
        for (int i = 0; i < NUM_ITERATIONS; i++)
        {
            /* Pick random slot, see if it's got something in it; if not, create it.  If so,
             * delete it. */
            final int slot = ThreadLocalRandom.current().nextInt(NUM_SUBS);
            synchronized (locks[slot])
            {
                if (subs[slot] == null)
                {
                    subs[slot] = aeron.addSubscription(CHANNEL, slot + 1, this);
                }
                else
                {
                    subs[slot].close();
                    subs[slot] = null;
                }
            }
        }
    }
}
```

Sometimes, everything will work, and you'll see "Done!" and it'll exit.  Run it a couple more times, or just bump the NUM_ITERATIONS constant by 10x or so, and unfortunate things will begin to happen, like the test spitting out interesting exceptions (below is just one example, but there are others, including negative timeout values, etc.) and/or deciding the driver is now unresponsive; e.g.:

```
java.lang.IllegalStateException: Attempting to signal when signal has already been raised
	at uk.co.real_logic.agrona.concurrent.Signal.signal(Signal.java:34)
	at uk.co.real_logic.aeron.ClientConductor.operationSucceeded(ClientConductor.java:265)
	at uk.co.real_logic.aeron.DriverListenerAdapter.onMessage(DriverListenerAdapter.java:104)
	at uk.co.real_logic.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:84)
	at uk.co.real_logic.aeron.DriverListenerAdapter.receiveMessages(DriverListenerAdapter.java:56)
	at uk.co.real_logic.aeron.ClientConductor.doWork(ClientConductor.java:104)
	at uk.co.real_logic.agrona.concurrent.AgentRunner.run(AgentRunner.java:83)
	at java.lang.Thread.run(Thread.java:745)
uk.co.real_logic.aeron.exceptions.DriverTimeoutException: Driver has been inactive for over 10000ms
	at uk.co.real_logic.aeron.ClientConductor.checkDriverHeartbeat(ClientConductor.java:353)
	at uk.co.real_logic.aeron.ClientConductor.onKeepalive(ClientConductor.java:338)
	at uk.co.real_logic.aeron.ClientConductor$$Lambda$4/1225358173.run(Unknown Source)
	at uk.co.real_logic.agrona.TimerWheel.expireTimers(TimerWheel.java:234)
	at uk.co.real_logic.aeron.ClientConductor.processTimers(ClientConductor.java:329)
	at uk.co.real_logic.aeron.ClientConductor.doWork(ClientConductor.java:103)
	at uk.co.real_logic.agrona.concurrent.AgentRunner.run(AgentRunner.java:83)
	at java.lang.Thread.run(Thread.java:745)

***
*** Timeout from the Media Driver - is it currently running? Exiting.
***
```

Meanwhile, once the driver gets into that state, it appears to be forevermore unresponsive, stuck here:

```
"driver-conductor" #13 prio=5 os_prio=31 tid=0x00007fa22b8cb000 nid=0x5903 runnable [0x0000000122ff6000]
   java.lang.Thread.State: RUNNABLE
	at uk.co.real_logic.agrona.concurrent.ringbuffer.ManyToOneRingBuffer.waitForMsgLengthVolatile(ManyToOneRingBuffer.java:312)
	at uk.co.real_logic.agrona.concurrent.ringbuffer.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:137)
	at uk.co.real_logic.agrona.concurrent.ringbuffer.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:112)
	at uk.co.real_logic.aeron.driver.DriverConductor.doWork(DriverConductor.java:224)
	at uk.co.real_logic.agrona.concurrent.AgentRunner.run(AgentRunner.java:83)
	at java.lang.Thread.run(Thread.java:745)
```

If you control-c the driver, you get plenty of these forever:

```
timeout await for agent. Retrying...
timeout await for agent. Retrying...
timeout await for agent. Retrying...
timeout await for agent. Retrying...
timeout await for agent. Retrying...
```

But it doesn't actually quit.

**Comment by tmontgomery** [comment]
Several changes should address this.

Would you be so kind as to retest?

**Comment by tmontgomery** [comment]
As the client has been redone and have not heard from a retest, going to close. If this still occurs with latest, let us know.
