### ISSUE TITLE
Non Deterministic System Test Failure

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/Aeron#116]
uk.co.real_logic.aeron.PubAndSubTest > shouldReceivePublishedMessageOneForOneWithReSubscription FAILED
    org.junit.experimental.theories.internal.ParameterizedAssertionError: shouldReceivePublishedMessageOneForOneWithReSubscription("udp://localhost:54325" <from UNICAST_URI>)

        Caused by:
        org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
            at java.lang.Object.wait(Native Method)
            at uk.co.real_logic.agrona.concurrent.Signal.await(Signal.java:53)
            at uk.co.real_logic.aeron.ClientConductor.await(ClientConductor.java:288)
            at uk.co.real_logic.aeron.ClientConductor.awaitOperationSucceeded(ClientConductor.java:298)
            at uk.co.real_logic.aeron.ClientConductor.addSubscription(ClientConductor.java:164)
            at uk.co.real_logic.aeron.Aeron.addSubscription(Aeron.java:188)
            at uk.co.real_logic.aeron.PubAndSubTest.shouldReceivePublishedMessageOneForOneWithReSubscription(PubAndSubTest.java:599)
Results: FAILURE (16 tests, 15 successes, 1 failures, 0 skipped)

**Comment by tmontgomery** [comment]
Is it always this particular test? Or is it sometimes others? Just trying to understand. I don't see it, so...

**Comment by mjpt777** [comment]
I've also seen it on the pongTest on a constrained ultrabook.

**Comment by tmontgomery** [comment]
@mjpt777 that was also Windows 7, correct? Not that I think it should matter.

**Comment by mjpt777** [comment]
Correct.

**Comment by tmontgomery** [comment]
It is interesting that the stack trace has it waiting in `addSubscription` at the second stage. I wonder if this could be exposing some possible client side issue...

If it is always the same test and same stack trace, that is.

**Comment by mjpt777** [comment]
I wonder is it related to https://github.com/real-logic/Aeron/issues/112

**Comment by tmontgomery** [comment]
Quite possible.

**Comment by RichardWarburton** [comment]
Currently on my laptop and trying to reproduce the problem, but of course the build is now rock solid!

**Comment by mjpt777** [comment]
The signally mechanism in the client has been rewritten after we noticed a number of race conditions that can be explain this. I'll close for now and see if it reoccurs.
