### ISSUE TITLE
IllegalArgumentException when Aeron.addSubscription timeouts

### ISSUE THREAD

**Issue by lech-glowiak** [real-logic/Aeron#118]
ClientConductor uses Agrona's Signal to await for subscription addition.
Signal in turn throws IllegalArgumentException when it calls with negative argument (that is after timeout duration).

Also `private void ClientConductorTest.willSignalTimeOut()` should `throw new IllegalArgumentException("timeout cannot be negative");`
instead of returning null.
Maybe this should be fixed in Agrona: other 'await' method that checks if timeout has passed and returns boolean?

**Comment by mjpt777** [comment]
Can you prove a simple test case?

**Comment by lech-glowiak** [comment]
This happens one time per few runs. This exception is thrown concurrently to exception from Agrona's AgentRunner - which is also fatal.

Code is here:
https://github.com/lech-glowiak/Aeron/blob/master/aeron-system-tests/src/test/java/uk/co/real_logic/aeron/FailExample.java

That is output on specific run at Windows 7, i3 processor, JDK8.
```
WARNING: aeron directory already exists: C:\Users\kot\AppData\Local\Temp\aeron
Closing driver: 2197
calling addSubscription: 2275
java.lang.IllegalArgumentException: timeout value is negative: 12290
java.lang.IllegalArgumentException: timeout value is negative
	at java.lang.Object.wait(Native Method)
	at uk.co.real_logic.agrona.concurrent.Signal.await(Signal.java:53)
	at uk.co.real_logic.aeron.ClientConductor.await(ClientConductor.java:288)
	at uk.co.real_logic.aeron.ClientConductor.awaitOperationSucceeded(ClientConductor.java:298)
	at uk.co.real_logic.aeron.ClientConductor.addSubscription(ClientConductor.java:164)
	at uk.co.real_logic.aeron.Aeron.addSubscription(Aeron.java:187)
	at FailExample.main(FailExample.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
uk.co.real_logic.aeron.exceptions.DriverTimeoutException: Driver has been inactive for over 10000ms
	at uk.co.real_logic.aeron.ClientConductor.checkDriverHeartbeat(ClientConductor.java:353)
	at uk.co.real_logic.aeron.ClientConductor.onKeepalive(ClientConductor.java:338)
	at uk.co.real_logic.aeron.ClientConductor$$Lambda$49/1971489295.run(Unknown Source)
	at uk.co.real_logic.agrona.TimerWheel.expireTimers(TimerWheel.java:234)
	at uk.co.real_logic.aeron.ClientConductor.processTimers(ClientConductor.java:329)
	at uk.co.real_logic.aeron.ClientConductor.doWork(ClientConductor.java:103)
	at uk.co.real_logic.agrona.concurrent.AgentRunner.run(AgentRunner.java:83)
	at java.lang.Thread.run(Thread.java:745)

***
*** Timeout from the Media Driver - is it currently running? Exiting.
***
```

**Comment by tmontgomery** [comment]
Thanks!

We plan to redo how the client conductor handles this. And will most likely be eliminating Signal usage and making it much simpler.

**Comment by tmontgomery** [comment]
The client API model has been redone. With the elimination of Signal, this should act differently.

Would you be so kind as to retest this with the latest?

**Comment by tmontgomery** [comment]
With the latest, this does not throw the signal error. It does throw the driver inactive timeout as one would expect from the code. So, this appears to be addressed.
