### ISSUE TITLE
Gradle build: agent test failed

### ISSUE THREAD

**Issue by KelvinYin** [real-logic/aeron#1185]
```
./gradlew

DriverLoggingAgentTest > logAllIpcChannel() FAILED
    java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "io/aeron/driver/NameResolver"
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at io.aeron.agent.DriverLoggingAgentTest.testLogMediaDriverEvents(DriverLoggingAgentTest.java:141)
        at io.aeron.agent.DriverLoggingAgentTest.logAllIpcChannel(DriverLoggingAgentTest.java:95)

529 tests completed, 1 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':aeron-agent:test'.
> There were failing tests. See the report at: file:///Users/yinkangxi/opensource/aeron/aeron-agent/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
```

**Comment by mjpt777** [comment]
Not sure what JDK you are running ? We run this successfully across many JDK versions as you can see from CI - https://github.com/real-logic/aeron/actions/runs/888762063

**Comment by KelvinYin** [comment]
> Not sure what JDK you are running ? We run this successfully across many JDK versions as you can see from CI - https://github.com/real-logic/aeron/actions/runs/888762063

This is my JDK version:
```
java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

**Comment by mjpt777** [comment]
Have you modified the build or source in some way?

**Comment by KelvinYin** [comment]
No, I did not do anything. 

All I have done were git clone the repository and run the gradlew command on the console.

**Comment by KelvinYin** [comment]
I upgrade my JDK version from 1.8.0_201 to 1.8.0_291, there is still the same error.

**Comment by mjpt777** [comment]
Try pulling the latest from main and building again.

**Comment by KelvinYin** [comment]
Yes, there is no errors in the latest code. But I do not know what the reason is.
