### ISSUE TITLE
IllegalStateException: Attempting to signal when signal has already been raised

### ISSUE THREAD

**Issue by strangelydim** [real-logic/Aeron#126]
Start up a media driver, and then start ... well, probably any app that registers a SIGINT handler; let's use SubscriberTool as an example:

```
java -cp aeron-tools/build/libs/tools.jar uk.co.real_logic.aeron.tools.SubscriberTool
```

and then hit control-c pretty quickly multiple times right after the app starts up.  (You might have to try a couple times to get the timing right.)

You should get one - or more - of these:

```
java.lang.IllegalStateException: Attempting to signal when signal has already been raised
	at uk.co.real_logic.agrona.concurrent.Signal.signal(Signal.java:34)
	at uk.co.real_logic.aeron.ClientConductor.operationSucceeded(ClientConductor.java:263)
	at uk.co.real_logic.aeron.DriverListenerAdapter.onMessage(DriverListenerAdapter.java:104)
	at uk.co.real_logic.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:84)
	at uk.co.real_logic.aeron.DriverListenerAdapter.receiveMessages(DriverListenerAdapter.java:56)
	at uk.co.real_logic.aeron.ClientConductor.doWork(ClientConductor.java:102)
	at uk.co.real_logic.agrona.concurrent.AgentRunner.run(AgentRunner.java:83)
	at java.lang.Thread.run(Thread.java:745)
```

Probably not a huge issue - it's likely to be more cosmetic than anything - but it'd be nice if just hitting control-c a couple times worked correctly, silently, without spitting out an exception.

**Comment by tmontgomery** [comment]
In the past, this has indicated further problems with the client threading model.

However, major changes coming here soon. So, this will probably be going away as we plan to eliminate Signal usage.

**Comment by strangelydim** [comment]
I'm all for these upcoming changes to get rid of using Signal as a means of synchronizing threads...

**Comment by mjpt777** [comment]
Signal is no longer used.
