### ISSUE TITLE
aeron build failure and Error: Could not find or load main class io.aeron.driver.MediaDriver is seen on JDK17

### ISSUE THREAD

**Issue by spshuklaji** [real-logic/aeron#1262]
I tried to build Aeron 1.36.0 from source code using JDK-17, and then perform some performance tests.
But the Aeron build failed as below:
Command:
```
./gradlew
```
Failure
```
/src/aeron/aeron-cluster/build/generated-src/io/aeron/cluster/codecs/AppendPositionDecoder.java:181: warning: no comment
    public long leadershipTermId()
                ^
/src/aeron/aeron-cluster/build/generated-src/io/aeron/cluster/codecs/AppendPositionDecoder.java:151: warning: no comment
    public static int leadershipTermIdEncodingLength()
                      ^
/src/aeron/aeron-cluster/build/generated-src/io/aeron/cluster/codecs/AppendPositionDecoder.java:146: warning: no comment
    public static int leadershipTermIdEncodingOffset()
                      ^
100 warnings
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
/src/aeron/aeron-driver/src/main/java/io/aeron/driver/OptimalMulticastDelayGenerator.java:68: warning: empty <p> tag
     * <p>
       ^
1 warning
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

UdpChannelTest > shouldGetProtocolFamilyForIpV6() FAILED
    io.aeron.driver.exceptions.InvalidChannelException: java.lang.IllegalArgumentException: Unable to find multicast interface matching criteria: /[0:0:0:0:0:0:0:1]:0/128
        at app//io.aeron.driver.media.UdpChannel.parse(UdpChannel.java:292)
        at app//io.aeron.driver.media.UdpChannel.parse(UdpChannel.java:113)
        at app//io.aeron.driver.UdpChannelTest.shouldGetProtocolFamilyForIpV6(UdpChannelTest.java:340)

        Caused by:
        java.lang.IllegalArgumentException: Unable to find multicast interface matching criteria: /[0:0:0:0:0:0:0:1]:0/128
            at io.aeron.driver.media.UdpChannel.findInterface(UdpChannel.java:915)
            at io.aeron.driver.media.UdpChannel.parse(UdpChannel.java:265)
            ... 2 more

UdpChannelTest > shouldHandleIpV6CanonicalFormForUnicastCorrectly(String, String) > io.aeron.driver.UdpChannelTest.shouldHandleIpV6CanonicalFormForUnicastCorrectly(String, String)[1] FAILED
    io.aeron.driver.exceptions.InvalidChannelException: java.lang.IllegalArgumentException: Unable to find multicast interface matching criteria: /[0:0:0:0:0:0:0:1]:0/128
        at app//io.aeron.driver.media.UdpChannel.parse(UdpChannel.java:292)
        at app//io.aeron.driver.media.UdpChannel.parse(UdpChannel.java:113)
        at app//io.aeron.driver.UdpChannelTest.shouldHandleIpV6CanonicalFormForUnicastCorrectly(UdpChannelTest.java:299)

        Caused by:
        java.lang.IllegalArgumentException: Unable to find multicast interface matching criteria: /[0:0:0:0:0:0:0:1]:0/128
            at io.aeron.driver.media.UdpChannel.findInterface(UdpChannel.java:915)
            at io.aeron.driver.media.UdpChannel.parse(UdpChannel.java:265)
            ... 2 more

UdpChannelTest > shouldHandleIpV6CanonicalFormForMulticastCorrectly(String, String) > io.aeron.driver.UdpChannelTest.shouldHandleIpV6CanonicalFormForMulticastCorrectly(String, String)[1] FAILED
    io.aeron.driver.exceptions.InvalidChannelException: java.lang.IllegalArgumentException: Unable to find multicast interface matching criteria: /[0:0:0:0:0:0:0:1]:54321/64
        at app//io.aeron.driver.media.UdpChannel.parse(UdpChannel.java:292)
        at app//io.aeron.driver.media.UdpChannel.parse(UdpChannel.java:113)
        at app//io.aeron.driver.UdpChannelTest.shouldHandleIpV6CanonicalFormForMulticastCorrectly(UdpChannelTest.java:439)

        Caused by:
        java.lang.IllegalArgumentException: Unable to find multicast interface matching criteria: /[0:0:0:0:0:0:0:1]:54321/64
            at io.aeron.driver.media.UdpChannel.findInterface(UdpChannel.java:915)
            at io.aeron.driver.media.UdpChannel.parse(UdpChannel.java:218)
            ... 2 more

283 tests completed, 3 failed 

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':aeron-driver:test'.
> There were failing tests. See the report at: file:///src/aeron/aeron-driver/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 13s
```

This failure is preceded by number of warning as below:
```
/src/aeron/aeron-cluster/build/generated-src/io/aeron/cluster/codecs/AppendPositionDecoder.java:243: warning: no comment
    public static int followerMemberIdSinceVersion()
                      ^
/src/aeron/aeron-cluster/build/generated-src/io/aeron/cluster/codecs/AppendPositionDecoder.java:57: warning: no comment
    public int initialOffset()
               ^
/src/aeron/aeron-cluster/build/generated-src/io/aeron/cluster/codecs/AppendPositionDecoder.java:181: warning: no comment
    public long leadershipTermId()
                ^
/src/aeron/aeron-cluster/build/generated-src/io/aeron/cluster/codecs/AppendPositionDecoder.java:151: warning: no comment
    public static int leadershipTermIdEncodingLength()
                      ^
/src/aeron/aeron-cluster/build/generated-src/io/aeron/cluster/codecs/AppendPositionDecoder.java:146: warning: no comment
    public static int leadershipTermIdEncodingOffset()
                      ^
100 warnings
```

But the jar file is generated:
```
$ ls aeron-all/build/libs/aeron-all-1.36.0.jar
aeron-all/build/libs/aeron-all-1.36.0.jar
```

And when I executed the command it failed as below:
```
$JAVA_HOME/bin/java -cp /src/aeron-all/build/libs/aeron-all-1.27.0.jar -Daeron.dir=/dev/shm/aeron-root io.aeron.driver.MediaDriver
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Error: Could not find or load main class io.aeron.driver.MediaDriver
Caused by: java.lang.ClassNotFoundException: io.aeron.driver.MediaDriver
```

I have been using Aeron 1.27.0 (Gradle 6.3), using the following commands and the results are okay.

```
gradle -g /src --console='plain' --stacktrace assemble --continue
```
```
$JAVA_HOME/bin/java -cp /src/aeron-all/build/libs/aeron-all-1.27.0.jar -Daeron.dir=/dev/shm/aeron-root io.aeron.driver.MediaDriver 
$JAVA_HOME/bin/java -cp /src/aeron-all/build/libs/aeron-all-1.27.0.jar -Daeron.sample.messages=100 io.aeron.samples.BasicSubscriber
$JAVA_HOME/bin/java -cp /src/aeron-all/build/libs/aeron-all-1.27.0.jar -Daeron.sample.messages=100 io.aeron.samples.BasicPublisher 
```
Attached complete logs:
[aeron.txt](https://github.com/real-logic/aeron/files/7609160/aeron.txt)

Is it possible to get similar behavior with Latest Aeron and JDK 17? Also, what is the right way to perform these tests?

**Comment by mikeb01** [comment]
This error:
```    io.aeron.driver.exceptions.InvalidChannelException: java.lang.IllegalArgumentException: Unable to find multicast interface matching criteria: /[0:0:0:0:0:0:0:1]:0/128```

Is because there is no IPv6 address bound to any of your local interfaces.  I'll add an assumption to disable this test.  In the interim you can add `@Disabled` to those tests.

> But the jar file is generated:

```$ ls aeron-all/build/libs/aeron-all-1.36.0.jar
aeron-all/build/libs/aeron-all-1.36.0.jar```

> And when I executed the command it failed as below:

```$JAVA_HOME/bin/java -cp /src/aeron-all/build/libs/aeron-all-1.27.0.jar -Daeron.dir=/dev/shm/aeron-root io.aeron.driver.MediaDriver
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Error: Could not find or load main class io.aeron.driver.MediaDriver
Caused by: java.lang.ClassNotFoundException: io.aeron.driver.MediaDriver```

This is because the file generated is `aeron-all-1.36.0.jar` and you are trying to run it with `aeron-all-1.27.0.jar` which doesn't exist.
