### ISSUE TITLE
Exception in thread "[sender,receiver,driver-conductor]" java.lang.NoClassDefFoundError: io/aeron/logbuffer/FrameDescriptor

### ISSUE THREAD

**Issue by JulienBe** [real-logic/aeron#1288]
Hello !

So first, I'm probably doing something I'm not supposed to do. It was just to poking at Aeron. And it's not a big deal.

# Issue

What I'm doing is:

1. Start Aeron, open a **sub** `aeron:udp?endpoint=0.0.0.0:0`
2. On the same machine, start Aeron again, and this time create a **pub** `aeron:udp?endpoint=127.0.0.1:xyz` where xyz will be the port randomly assigned the Aeron1's sub.

What I wasn't excepting was to get this error:

```
Starting pub
Exception in thread "[sender,receiver,driver-conductor]" java.lang.NoClassDefFoundError: io/aeron/logbuffer/FrameDescriptor
	at io.aeron.driver.media.UdpChannelTransport.isValidFrame(UdpChannelTransport.java:372)
	at io.aeron.driver.media.DataTransportPoller.poll(DataTransportPoller.java:211)
	at io.aeron.driver.media.DataTransportPoller.pollTransports(DataTransportPoller.java:93)
	at io.aeron.driver.Receiver.doWork(Receiver.java:104)
	at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:120)
	at org.agrona.concurrent.AgentRunner.doWork(AgentRunner.java:304)
	at org.agrona.concurrent.AgentRunner.workLoop(AgentRunner.java:296)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:162)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: io.aeron.logbuffer.FrameDescriptor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 9 more
```	
# Versions

```
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8)
OpenJDK 64-Bit Server VM (build 11.0.13+8, mixed mode)
```
```gradle
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.6.10"
    implementation 'io.aeron:aeron-all:1.37.0'
}
```

# Code

Here is an extract from the code, the full source is [here](https://github.com/JulienBe/aeron-poking):

```kotlin
  val idleStrategy: IdleStrategy = SleepingMillisIdleStrategy(100)
  val barrier = ShutdownSignalBarrier()
  val mediaDriverCtx = MediaDriver.Context()
    .aeronDirectoryName(CommonContext.getAeronDirectoryName() + "-${System.currentTimeMillis()}")
    .dirDeleteOnStart(true)
    .dirDeleteOnShutdown(true)
    .threadingMode(ThreadingMode.SHARED)
  val mediaDriver = MediaDriver.launchEmbedded(mediaDriverCtx)
  val aeronCtx = Aeron.Context().aeronDirectoryName(mediaDriver.aeronDirectoryName())
  val aeron = Aeron.connect(aeronCtx)
```
```kotlin
  fun pub(pubStr: String) { // "aeron:udp?endpoint=127.0.0.1:xyz"
    val pubAgent = object : Agent {
      val pub = aeron.addExclusivePublication(pubStr, streamId)
      override fun doWork(): Int {
        if (!pub.isConnected)    println("not connected: $pub")
        else                     pub.offer(ExpandableDirectByteBuffer(512))
        return 0
      }
      override fun roleName(): String {        return "sendAgent"      }
    }
    val pubAgentRunner = AgentRunner(idleStrategy, {obj: Throwable -> obj.printStackTrace() }, null, pubAgent)
    AgentRunner.startOnThread(pubAgentRunner)
    waitNClose(listOf(pubAgentRunner))
  }
```
```kotlin
  fun sub(subStr: String) {
    val subAgent = object : Agent {
      val sub = aeron.addSubscription(subStr, streamId)
      val handler = FragmentHandler { buffer, offset, length, header -> println("Received") }
      override fun doWork(): Int {        return sub.poll(handler, 1)      }
      override fun roleName(): String {        return "SubAgent"      }
    }
    val subAgentRunner = AgentRunner(idleStrategy, { obj: Throwable -> obj.printStackTrace() }, null, subAgent)
    AgentRunner.startOnThread(subAgentRunner)
    waitNClose(listOf(subAgentRunner))
  }
```

Thanks for your time :bow:

**Comment by vyazelenko** [comment]
I've tested your repo and it worked without a problem both in Intellij and when I build the standalone Shadow jar. It seems you had some issue build issue.
Please use [StackOverflow](https://stackoverflow.com/questions/tagged/aeron) to ask questions about Aeron usage.

**Comment by JulienBe** [comment]
Hmm, weird.

It's only when I point to the port randomly assigned. It consistently works fine in other cases and I get messages passing between my instances.

Anyway, it was just a random test, thanks for your time :)
