### ISSUE TITLE
Java Media Driver exceptions - ControlProtocolException and IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ww3456** [real-logic/aeron#1315]
One of our Media Drivers has become unresponsive and appears to be continuously logging ControlProtocolException and IndexOutOfBoundsException. Any idea what might have caused this? 

```
***
142957971 observations from 2022-04-28 06:28:59.465+0100 to 2022-04-28 12:52:16.759+0100 for:
 io.aeron.exceptions.ControlProtocolException: command typeId=0 unknown, correlationId=0
        at io.aeron.driver.ClientCommandAdapter.onMessage(ClientCommandAdapter.java:257)
        at org.agrona.concurrent.ringbuffer.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:145)
        at io.aeron.driver.ClientCommandAdapter.receive(ClientCommandAdapter.java:66)
        at io.aeron.driver.DriverConductor.doWork(DriverConductor.java:177)
        at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:114)
        at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
        at java.base/java.lang.Thread.run(Thread.java:830)

***
71478987 observations from 2022-04-28 07:40:00.354+0100 to 2022-04-28 12:52:16.760+0100 for:
 java.lang.IndexOutOfBoundsException: index=938712 length=1869768048 capacity=1049344
        at org.agrona.concurrent.UnsafeBuffer.boundsCheck0(UnsafeBuffer.java:1730)
        at org.agrona.concurrent.UnsafeBuffer.setMemory(UnsafeBuffer.java:302)
        at org.agrona.concurrent.ringbuffer.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:152)
        at io.aeron.driver.ClientCommandAdapter.receive(ClientCommandAdapter.java:66)
        at io.aeron.driver.DriverConductor.doWork(DriverConductor.java:177)
        at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:114)
        at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:291)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
        at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by mjpt777** [comment]
Can you provide more details on what Java version, platform, Aeron version on both client and driver, etc.? Plus some context on what actions were being taken when this happened.

**Comment by mjpt777** [comment]
The stats on this show you have a serious under resourcing issue on this server. 153 of your Aeron clients have timed out due to being starved of CPU or experiencing long GC pauses. One of them was part way through sending a control message and had to be unblocked and probably came back as a zombie and corrupted the ring buffer. 

I would recommend you do some capacity planning and put in monitoring to avoid such issues. One client timeout would have triggered me to take action. 153 client timeouts is being asleep at the wheel in the context of monitoring a production system.
