### ISSUE TITLE
Gradle build: agent test failed

### ISSUE THREAD

**Issue by dpemon** [real-logic/aeron#1358]
jdk version:
```
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)
```

./gradlew

```
ClusterEventLoggerTest > logCatchupPositionLongCatchupEndpoint() FAILED
    java.lang.AssertionError:
    Expected: a string matching the pattern '\[[0-9]*\.[0-9]*] CLUSTER: CATCHUP_POSITION \[[0-9]*/8256]: memberId=-7 leadershipTermId=1233 logPosition=100 catchupEndpoint=aeron:udp\?endpoint=localhost:9090\|alias=(x)*\.\.\.'
         but: was "[4.0535281181270204E7] CLUSTER: CATCHUP_POSITION [4079/8256]: memberId=-7 leadershipTermId=1233 logPosition=100 catchupEndpoint=aeron:udp?endpoint=localhost:9090|alias=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx..."
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at io.aeron.agent.ClusterEventLoggerTest.logCatchupPositionLongCatchupEndpoint(ClusterEventLoggerTest.java:250)

ClusterEventLoggerTest > logDynamicJoinStateChange() FAILED
    java.lang.AssertionError:
    Expected: a string matching the pattern '\[[0-9]+\.[0-9]+] CLUSTER: DYNAMIC_JOIN_STATE_CHANGE \[26/26]: memberId=42 MINUTES -> SECONDS'
         but: was "[4.05352812440019E7] CLUSTER: DYNAMIC_JOIN_STATE_CHANGE [26/26]: memberId=42 MINUTES -> SECONDS"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at io.aeron.agent.ClusterEventLoggerTest.logDynamicJoinStateChange(ClusterEventLoggerTest.java:566)

ClusterEventLoggerTest > logCommitPosition() FAILED
    java.lang.AssertionError:
    Expected: a string matching the pattern '\[[0-9]+\.[0-9]+] CLUSTER: COMMIT_POSITION \[24/24]: memberId=2 leadershipTermId=1233 logPosition=988723465 leaderId=982374'
         but: was "[4.053528125262908E7] CLUSTER: COMMIT_POSITION [24/24]: memberId=2 leadershipTermId=1233 logPosition=988723465 leaderId=982374"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at io.aeron.agent.ClusterEventLoggerTest.logCommitPosition(ClusterEventLoggerTest.java:455)

ClusterEventLoggerTest > testLogAddPassiveMember() FAILED
    java.lang.AssertionError:
    Expected: a string matching the pattern '\[[0-9]+\.[0-9]+] CLUSTER: ADD_PASSIVE_MEMBER \[90/90]: memberId=42 correlationId=28397456 memberEndpoints=localhost:20113,localhost:20223,localhost:20333,localhost:0,localhost:8013'
         but: was "[4.053528130155351E7] CLUSTER: ADD_PASSIVE_MEMBER [90/90]: memberId=42 correlationId=28397456 memberEndpoints=localhost:20113,localhost:20223,localhost:20333,localhost:0,localhost:8013"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at io.aeron.agent.ClusterEventLoggerTest.testLogAddPassiveMember(ClusterEventLoggerTest.java:490)

ClusterEventLoggerTest > logAppendPosition() FAILED
    java.lang.AssertionError:
    Expected: a string matching the pattern '\[[0-9]+\.[0-9]+] CLUSTER: APPEND_POSITION \[21/21]: memberId=982374 leadershipTermId=1233 logPosition=988723465 flags=0b00000001'
         but: was "[4.053528133568345E7] CLUSTER: APPEND_POSITION [21/21]: memberId=982374 leadershipTermId=1233 logPosition=988723465 flags=0b00000001"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at io.aeron.agent.ClusterEventLoggerTest.logAppendPosition(ClusterEventLoggerTest.java:422)

ClusterEventLoggerTest > testLogAppendSessionClose() FAILED
    java.lang.AssertionError:
    Expected: a string matching the pattern '\[[0-9]+\.[0-9]+] CLUSTER: APPEND_SESSION_CLOSE \[55/55]: memberId=829374 sessionId=289374 closeReason=TIMEOUT leadershipTermId=2039842 timestamp=29384 timeUnit=MILLISECONDS'
         but: was "[4.0535281346977085E7] CLUSTER: APPEND_SESSION_CLOSE [55/55]: memberId=829374 sessionId=289374 closeReason=TIMEOUT leadershipTermId=2039842 timestamp=29384 timeUnit=MILLISECONDS"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at io.aeron.agent.ClusterEventLoggerTest.testLogAppendSessionClose(ClusterEventLoggerTest.java:538)

ClusterEventLoggerTest > logCatchupPosition() FAILED
    java.lang.AssertionError:
    Expected: a string matching the pattern '\[[0-9]+\.[0-9]+] CLUSTER: CATCHUP_POSITION \[57/57]: memberId=18 leadershipTermId=1233 logPosition=100 catchupEndpoint=aeron:udp\?endpoint=localhost:9090'
         but: was "[4.053528137604954E7] CLUSTER: CATCHUP_POSITION [57/57]: memberId=18 leadershipTermId=1233 logPosition=100 catchupEndpoint=aeron:udp?endpoint=localhost:9090"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at io.aeron.agent.ClusterEventLoggerTest.logCatchupPosition(ClusterEventLoggerTest.java:222)

ClusterEventLoggerTest > logStopCatchup() FAILED
    java.lang.AssertionError:
    Expected: a string matching the pattern '\[[0-9]+\.[0-9]+] CLUSTER: STOP_CATCHUP \[12/12]: memberId=42 leadershipTermId=1233'
         but: was "[4.053528138674967E7] CLUSTER: STOP_CATCHUP [12/12]: memberId=42 leadershipTermId=1233"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at io.aeron.agent.ClusterEventLoggerTest.logStopCatchup(ClusterEventLoggerTest.java:277)

ClusterEventLoggerTest > logReplayNewLeadershipTerm() FAILED
    java.lang.AssertionError:
    Expected: a string matching the pattern '\[[0-9]+\.[0-9]+] CLUSTER: REPLAY_NEW_LEADERSHIP_TERM \[59/59]: memberId=982374 isInElection=true leadershipTermId=1233 logPosition=988723465 termBaseLogPosition=988723433 appVersion=13 timestamp=890723452345 timeUnit=NANOSECONDS'
         but: was "[4.05352814039239E7] CLUSTER: REPLAY_NEW_LEADERSHIP_TERM [59/59]: memberId=982374 isInElection=true leadershipTermId=1233 logPosition=988723465 termBaseLogPosition=988723433 appVersion=13 timestamp=890723452345 timeUnit=NANOSECONDS"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at io.aeron.agent.ClusterEventLoggerTest.logReplayNewLeadershipTerm(ClusterEventLoggerTest.java:388)

590 tests completed, 9 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':aeron-agent:test'.
> There were failing tests. See the report at: file:///data/aeron/aeron-agent/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```

**Comment by vyazelenko** [comment]
Fixed with https://github.com/real-logic/aeron/commit/db3e56d7e4d410b774f82f6fe7bc4f6f4f4f25a4.
