### ISSUE TITLE
archive.catalog grows to 2GiB when calling ArchiveTool.compact()

### ISSUE THREAD

**Issue by pcdv** [real-logic/aeron#1391]
**EDIT: the problem is not due to restarting a node, but to calling ArchiveTool.compact() on the node's archive.**

I have observed the following behavior regarding the size of archive.catalog file (which is by default 1M according to Archive.Context):

```
# after starting a 3-node cluster for the first time
pcdv ~/environments/AERON/processes$ du AERON-NODE*/run/archive -h
387M    AERON-NODE/run/archive
387M    AERON-NODE-1/run/archive
387M    AERON-NODE-2/run/archive

# after killing NODE-2 (leader)
pcdv ~/environments/AERON/processes$ du AERON-NODE*/run/archive -h
387M    AERON-NODE/run/archive
387M    AERON-NODE-1/run/archive
387M    AERON-NODE-2/run/archive

# after restarting NODE-2
pcdv ~/environments/AERON/processes$ du AERON-NODE*/run/archive -h
387M    AERON-NODE/run/archive
387M    AERON-NODE-1/run/archive
2,7G    AERON-NODE-2/run/archive

pcdv ~/environments/AERON/processes$ ls -lh AERON-NODE-2/run/archive/
total 2,7G
-rw-r--r-- 1 pcdv 197121 128M déc.  14 17:27 0-0.rec
-rw-r--r-- 1 pcdv 197121 128M déc.  14 17:27 1-0.rec
-rw-r--r-- 1 pcdv 197121 128M déc.  14 17:28 2-0.rec
-rw-r--r-- 1 pcdv 197121 128M déc.  14 17:28 3-0.rec
-rw-r--r-- 1 pcdv 197121 128M déc.  14 17:28 4-0.rec
-rw-r--r-- 1 pcdv 197121 2,0G déc.  14 17:28 archive.catalog
-rw-r--r-- 1 pcdv 197121 1,1M déc.  14 17:27 archive-mark.dat
```

After more tests, the same scenario is observed if the restarted node is not the leader, or if the cluster contains only one node.

I wonder if this sudden increase of catalog size is expected.

Thanks

PS: I also tried to reproduce it with pure aeron code by running basic-auction-cluster in aeron-samples but it looks like the samples are not up-to-date:

```
$ ./basic-auction-cluster
==> logs/cluster-0.log <==

==> logs/cluster-1.log <==

==> logs/cluster-2.log <==

==> logs/cluster-0.log <==
[873703.607834] log started 2022-12-14 17:52:37.373+0100

==> logs/cluster-1.log <==
[873703.681784] log started 2022-12-14 17:52:37.447+0100

==> logs/cluster-2.log <==
[873703.664966] log started 2022-12-14 17:52:37.430+0100
Exception in thread "main" io.aeron.exceptions.ConfigurationException: ERROR - Archive.Context.replicationChannel must be set
        at io.aeron.archive.Archive$Context.conclude(Archive.java:1001)
        at io.aeron.archive.Archive.<init>(Archive.java:77)
        at io.aeron.archive.Archive.launch(Archive.java:172)
        at io.aeron.cluster.ClusteredMediaDriver.launch(ClusteredMediaDriver.java:97)
        at io.aeron.samples.cluster.tutorial.BasicAuctionClusteredServiceNode.main(BasicAuctionClusteredServiceNode.java:199)
Exception in thread "main" io.aeron.exceptions.ConfigurationException: ERROR - Archive.Context.replicationChannel must be set
        at io.aeron.archive.Archive$Context.conclude(Archive.java:1001)
        at io.aeron.archive.Archive.<init>(Archive.java:77)
        at io.aeron.archive.Archive.launch(Archive.java:172)
        at io.aeron.cluster.ClusteredMediaDriver.launch(ClusteredMediaDriver.java:97)
        at io.aeron.samples.cluster.tutorial.BasicAuctionClusteredServiceNode.main(BasicAuctionClusteredServiceNode.java:199)
Exception in thread "main" io.aeron.exceptions.ConfigurationException: ERROR - Archive.Context.replicationChannel must be set
        at io.aeron.archive.Archive$Context.conclude(Archive.java:1001)
        at io.aeron.archive.Archive.<init>(Archive.java:77)
        at io.aeron.archive.Archive.launch(Archive.java:172)
        at io.aeron.cluster.ClusteredMediaDriver.launch(ClusteredMediaDriver.java:97)
        at io.aeron.samples.cluster.tutorial.BasicAuctionClusteredServiceNode.main(BasicAuctionClusteredServiceNode.java:199)
```

**Comment by vyazelenko** [comment]
@pcdv The `basic-auction-cluster` in `aeron-samples` is working now.

**Comment by pcdv** [comment]
Thanks @vyazelenko. I don't reproduce the problem with basic-auction-cluster, I guess I'll have to look closer at my implementation.

I'm closing the issue, I'll ping back if I find anything.

**Comment by pcdv** [comment]
It appears that the file grows from 1M to 2G when calling [ArchiveTool.compact()](https://github.com/real-logic/aeron/blob/10ce4c4160cb3172f85f2201648b8a5dd3d1f50b/aeron-archive/src/main/java/io/aeron/archive/ArchiveTool.java#L700-L700). Did not expect that!

**Comment by pcdv** [comment]
Yes it happens on this line: https://github.com/real-logic/aeron/blob/10ce4c4160cb3172f85f2201648b8a5dd3d1f50b/aeron-archive/src/main/java/io/aeron/archive/ArchiveTool.java#L739-L740

Knowing that, I suppose I have to check the file length before calling compact(), to do it only when the file is above this threshold.

Do you think ArchiveTool should be able to automatically truncate the catalog file to a smaller size if it is filled with zeros after a given position?

**Comment by vyazelenko** [comment]
@pcdv This is a bug. The compact command should produce a file whose length is less than or equal to that of the original Catalog file. I'll fix it.

**Comment by vyazelenko** [comment]
Fixed by https://github.com/real-logic/aeron/commit/03c3f7c7c1976019cca7030f9f4e02717acf117b.
