### ISSUE TITLE
Long running Media Driver becomes unresponsive

### ISSUE THREAD

**Issue by vksingh70** [real-logic/Aeron#140]
1> I started two separate media drivers on two different machines. 
       java -cp aeron-samples/build/libs/samples.jar -Daeron.dir=/dev/shm/vk/aeron uk.co.real_logic.aeron.driver.MediaDriver
2> Started 2 subscriber application  on 2 different channel/stream on machine-1
     java -cp aeron-samples/build/libs/samples.jar -Daeron.dir=/dev/shm/vk/aeron -Daeron.sample.channel=udp://192.168.14.34:9988 -Daeron.sample.streamId=120  uk.co.real_logic.aeron.samples.MultipleSubscribersWithFragmentAssembly

     java -cp aeron-samples/build/libs/samples.jar -Daeron.dir=/dev/shm/vk/aeron -Daeron.sample.channel=udp://226.168.14.33:8888 -Daeron.sample.streamId=20  uk.co.real_logic.aeron.samples.MultipleSubscribersWithFragmentAssembly

3> Started two producers on two different channel/stream on machine-2 with very slow data rate. One of the application just created a publisher, but did not send any data.
       java -cp aeron-samples/build/libs/samples.jar -Daeron.dir=/dev/shm/vk/aeron -Daeron.sample.channel=udp://226.168.14.33:8888 -Daeron.sample.streamId=20  uk.co.real_logic.aeron.samples.MultiplePublishersWithFragmentation
   (Modified the application to send very slow data rate)
      java -cp aeron-samples/build/libs/samples.jar -Daeron.dir=/dev/shm/vk/aeron -Daeron.sample.channel=udp://192.168.14.34:9988 -Daeron.sample.streamId=120  uk.co.real_logic.aeron.samples.MultiplePublishersWithFragmentation
4> let the program run over the weekend.

After 3 days, both the media drivers were unresponsive, but did not die. Both the publisher and subscriber had exited because of DriverTimeoutException.

**Comment by mjpt777** [comment]
Did you get a stack dump of the media driver to see what the threads were doing? You can do this with jstack.

**Comment by vksingh70** [comment]
I just took a dump for one of the Media Driver at the producer side. I will repeat the test and attach more dumps for comparison.
vsingh@cooper Aeron >jstack 12069
2015-05-27 08:54:44
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.5-b02 mixed mode):

"Attach Listener" #15 daemon prio=9 os_prio=0 tid=0x00007f6f58001000 nid=0x1e22 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"driver-conductor" #11 prio=5 os_prio=0 tid=0x00007f6f801ba800 nid=0x2f31 runnable [0x00007f6f5d845000]
   java.lang.Thread.State: RUNNABLE
        at uk.co.real_logic.agrona.concurrent.ringbuffer.ManyToOneRingBuffer.waitForMsgLengthVolatile(ManyToOneRingBuffer.java:312)
        at uk.co.real_logic.agrona.concurrent.ringbuffer.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:137)
        at uk.co.real_logic.agrona.concurrent.ringbuffer.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:112)
        at uk.co.real_logic.aeron.driver.DriverConductor.doWork(DriverConductor.java:224)
        at uk.co.real_logic.agrona.concurrent.AgentRunner.run(AgentRunner.java:92)
        at java.lang.Thread.run(Thread.java:745)

"Service Thread" #7 daemon prio=9 os_prio=0 tid=0x00007f6f800a9000 nid=0x2f2d runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007f6f800a5800 nid=0x2f2c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007f6f800a3800 nid=0x2f2b waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007f6f800a1800 nid=0x2f2a runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007f6f80072000 nid=0x2f29 in Object.wait() [0x00007f6f707fe000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:142)
        - locked <0x00000000ec712430> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:158)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007f6f8006d800 nid=0x2f28 in Object.wait() [0x00007f6f84159000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
        - locked <0x00000000ec7125e8> (a java.lang.ref.Reference$Lock)

"main" #1 prio=5 os_prio=0 tid=0x00007f6f80009000 nid=0x2f26 in Object.wait() [0x00007f6f85cb7000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Thread.join(Thread.java:1253)
        - locked <0x00000000ec7c3dc0> (a java.lang.Thread)
        at uk.co.real_logic.agrona.concurrent.AgentRunner.close(AgentRunner.java:130)
        at uk.co.real_logic.aeron.driver.MediaDriver$$Lambda$50/1327763628.accept(Unknown Source)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at uk.co.real_logic.aeron.driver.MediaDriver.close(MediaDriver.java:202)
        at uk.co.real_logic.aeron.driver.MediaDriver.main(MediaDriver.java:87)

"VM Thread" os_prio=0 tid=0x00007f6f80068800 nid=0x2f27 runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007f6f800ae000 nid=0x2f2e waiting on condition 

JNI global references: 283

**Comment by mjpt777** [comment]
Thanks, the stack trace was very useful. I was able to recreate this and have pushed a changed to Agrona that fixes an issue with the ManyToOneRingBuffer.

When we required a padding record that was exactly header length then the length field was set to zero which blocked the driver conductor forever. The length field now includes the header length. As an added bonus I changed the algorithm to not block on the consumer size if the producer takes an interrupt part why through writing a record which should make the driver conductor more responsive.

**Comment by tmontgomery** [comment]
Please retest and let us know if this is fixed.

**Comment by vksingh70** [comment]
I tried to retest the fix this morning and ran into similar issue. Looks like Media Driver (Producer side) is stuck and java process is running at 99.8 % cpu
vsingh@cooper SlowAeron >jstack 15265
2015-06-01 09:35:55
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.5-b02 mixed mode):

"Attach Listener" #12 daemon prio=9 os_prio=0 tid=0x00007f3268001000 nid=0x3c15 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"driver-conductor" #11 prio=5 os_prio=0 tid=0x00007f32901c8000 nid=0x3bad runnable [0x00007f3294314000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.Thread.yield(Native Method)
        at uk.co.real_logic.aeron.common.event.EventLogger.logException(EventLogger.java:186)
        at uk.co.real_logic.aeron.driver.DriverConductor.onClientCommand(DriverConductor.java:449)
        at uk.co.real_logic.aeron.driver.DriverConductor$$Lambda$34/764308918.onMessage(Unknown Source)
        at uk.co.real_logic.agrona.concurrent.ringbuffer.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:159)
        at uk.co.real_logic.agrona.concurrent.ringbuffer.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:117)
        at uk.co.real_logic.aeron.driver.DriverConductor.doWork(DriverConductor.java:243)
        at uk.co.real_logic.agrona.concurrent.AgentRunner.run(AgentRunner.java:93)
        at java.lang.Thread.run(Thread.java:745)

"receiver" #10 prio=5 os_prio=0 tid=0x00007f32901c6000 nid=0x3bac waiting on condition [0x00007f3294415000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
        at uk.co.real_logic.agrona.concurrent.BackoffIdleStrategy.idle(BackoffIdleStrategy.java:103)
        at uk.co.real_logic.agrona.concurrent.AgentRunner.run(AgentRunner.java:94)
        at java.lang.Thread.run(Thread.java:745)

"sender" #9 prio=5 os_prio=0 tid=0x00007f32901c4800 nid=0x3bab waiting on condition [0x00007f3294516000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
        at uk.co.real_logic.agrona.concurrent.BackoffIdleStrategy.idle(BackoffIdleStrategy.java:103)
        at uk.co.real_logic.agrona.concurrent.AgentRunner.run(AgentRunner.java:94)
        at java.lang.Thread.run(Thread.java:745)

"Service Thread" #7 daemon prio=9 os_prio=0 tid=0x00007f32900a7000 nid=0x3ba9 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007f32900a3800 nid=0x3ba8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007f32900a1800 nid=0x3ba7 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007f329009f800 nid=0x3ba6 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007f3290072000 nid=0x3ba5 in Object.wait() [0x00007f3295344000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000ec70f438> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:142)
        - locked <0x00000000ec70f438> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:158)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007f329006d800 nid=0x3ba4 in Object.wait() [0x00007f3295445000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000ec70f5f0> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)
        - locked <0x00000000ec70f5f0> (a java.lang.ref.Reference$Lock)

"main" #1 prio=5 os_prio=0 tid=0x00007f3290009000 nid=0x3ba2 waiting on condition [0x00007f32977a4000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:304)
        at uk.co.real_logic.agrona.concurrent.SigIntBarrier.await(SigIntBarrier.java:53)
        at uk.co.real_logic.aeron.driver.MediaDriver.main(MediaDriver.java:84)

"VM Thread" os_prio=0 tid=0x00007f3290068800 nid=0x3ba3 runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007f32900b4000 nid=0x3baa waiting on condition 

JNI global references: 286

**Comment by mjpt777** [comment]
Todd,

This looks like the consumer of the event log is not keeping up and is
blocking the consumer.

I was thinking that the event log should be a broadcast to avoid such
issues. What do you think?

Martin...

**Comment by tmontgomery** [comment]
Perhaps. However, couple questions:

1. Why is DriverConductor line 243 the event read and not the read of the command queue from Sender? This looks like not everything was updated to the latest in the run.

1. Why would the event log be having any data on it? I don't see `aeron.event.log` being set on the command line for the media driver.

**Comment by tmontgomery** [comment]
Sorry, was looking at wrong dump.

It is possible. But the event log should only be seeing exceptions. Which would indicate something else is going terribly wrong if it has that many exceptions.

**Comment by tmontgomery** [comment]
Wait, no... line 243 in DriverConductor is not a ManyToOneRingBuffer in the latest code.

https://github.com/real-logic/Aeron/blob/master/aeron-driver/src/main/java/uk/co/real_logic/aeron/driver/DriverConductor.java#L243

The stack doesn't jive with the latest code.

**Comment by vksingh70** [comment]
I have restarted the test with latest code from real-logic repo. Will update you tomorrow evening.

**Comment by vksingh70** [comment]
I did not see any problem with the latest code. Both the drivers were responsive after overnight run. This issue can be closed.
