### ISSUE TITLE
Issue running ArchivingMediaDriver under Java 17

### ISSUE THREAD

**Issue by adam-talos** [real-logic/aeron#1461]
I'm running into an issue with the module system preventing access to a private method in CRC32

```
Exception in thread "main" java.lang.Error: Failed to acquire method handle for private static native int java.util.zip.CRC32.updateByteBuffer0(int,long,int,int)
	at io.aeron.archive.checksum.Crc32.<clinit>(Crc32.java:54)
	at io.aeron.archive.checksum.Checksums.crc32(Checksums.java:32)
	at io.aeron.archive.checksum.Checksums.newInstance(Checksums.java:68)
	at io.aeron.archive.Archive$Context.concludeRecordChecksum(Archive.java:3151)
	at io.aeron.archive.Archive$Context.conclude(Archive.java:1303)
	at io.aeron.archive.Archive.<init>(Archive.java:81)
	at io.aeron.archive.Archive.launch(Archive.java:190)
	at io.aeron.archive.ArchivingMediaDriver.launch(ArchivingMediaDriver.java:94)
	at io.aeron.archive.ArchivingMediaDriver.main(ArchivingMediaDriver.java:55)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private static native int java.util.zip.CRC32.updateByteBuffer0(int,long,int,int) accessible: module java.base does not "opens java.util.zip" to unnamed module @136432db
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at io.aeron.archive.checksum.Crc32.<clinit>(Crc32.java:47)
	... 8 more
```

I'm not super familiar with the module system; is there a way to open up the module to allow access to this method?  I didn't see anything on the [compatibility page](https://aeroncookbook.com/cookbook-content/aeron-jdk16/).

**Comment by mikeb01** [comment]
Can you try with `--add-opens=java.base/java.util.zip=ALL-UNNAMED` added to the `java` command line parameters?

**Comment by adam-talos** [comment]
Thanks, Mike!  That worked perfectly.
