### ISSUE TITLE
multi cluster container onStart failed when has snapshot

### ISSUE THREAD

**Issue by liujingjun001** [real-logic/aeron#1466]
There are two clusterserviceContainer

io.aeron.cluster.client.ClusterException: FATAL - snapshot has incorrect pending message state: serviceId=0 nextServiceSessionId=-9223372036854775807 logServiceSessionId=-9223372036854775807 pendingMessageCount=0
	at io.aeron.cluster.PendingServiceMessageTracker.verify(PendingServiceMessageTracker.java:192) ~[aeron-all-1.41.2.jar!/:1.41.2]
	at io.aeron.cluster.ConsensusModuleAgent.loadSnapshot(ConsensusModuleAgent.java:2935) ~[aeron-all-1.41.2.jar!/:1.41.2]
	at io.aeron.cluster.ConsensusModuleAgent.recoverFromSnapshotAndLog(ConsensusModuleAgent.java:3746) ~[aeron-all-1.41.2.jar!/:1.41.2]
	at io.aeron.cluster.ConsensusModuleAgent.onStart(ConsensusModuleAgent.java:285) ~[aeron-all-1.41.2.jar!/:1.41.2]
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:150) ~[aeron-all-1.41.2.jar!/:1.41.2]
	at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_345]

**Comment by mikeb01** [comment]
We've run into this issue before and is generally cause by some form of non-determinism in the application code that calls `Cluster.offer`.  The most common case here is failing to retry in the face of `BACK_PRESSURE` or `ADMIN_ACTION` responses.

**Comment by mjpt777** [comment]
We have seen some customers use cluster services in a non-deterministic manner and to highlight potential divergence we added these checks. For customers on commercial support we can provide consultancy services and tooling to help correct issues in snapshots. If this is of interest then please contact sales@aeron.io.
