### ISSUE TITLE
Leader throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by NextToBe** [real-logic/aeron#1483]
we have some problem when using aeron-cluster in our production environment.

we have one three-node aeron-cluster application running on cent os with jdk8, and our version of aeron-cluster is 1.40.0

after the cluster running for about 10 hours,  the leader constantly throwing exceptions during driverConductor processing its work:

```
2023-07-13 04:00:01,070  [driver-conductor] ERROR c.t.a.a.c.u.SimpleLogErrorHandler  traceid= - Error: 
java.lang.IndexOutOfBoundsException: index=0 length=-1388900488 capacity=33554432
	at org.agrona.concurrent.UnsafeBuffer.boundsCheck0(UnsafeBuffer.java:2259)
	at org.agrona.concurrent.UnsafeBuffer.setMemory(UnsafeBuffer.java:337)
	at io.aeron.driver.PublicationImage.cleanBufferTo(PublicationImage.java:889)
	at io.aeron.driver.PublicationImage.trackRebuild(PublicationImage.java:547)
	at io.aeron.driver.DriverConductor.trackStreamPositions(DriverConductor.java:2059)
	at io.aeron.driver.DriverConductor.doWork(DriverConductor.java:218)
	at org.agrona.concurrent.AgentRunner.doWork(AgentRunner.java:292)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:165)
	at java.lang.Thread.run(Thread.java:748)
```

thanks for any help.

**Comment by JPWatson** [comment]
Hey @NextToBe. This is likely to be something specific to your environment and not possible to debug without additional context. In the first instance, I'd recommend upgrading to the latest version of Java and Aeron. 

Also, based on some of the overrides present, there are some configuration overrides you've made that we would not generally recommend. 

Given you're in production, it may be worth taking commercial support which would include help tracking down this kind of issue, fixes for previous versions of Aeron and advice on how to optimally configure the cluster for your use case. If you're interested, please send an email to info@aeron.io.

**Comment by NextToBe** [comment]
thanks
