### ISSUE TITLE
Issue with MediaDriver

### ISSUE THREAD

**Issue by PedroMPagani** [real-logic/aeron#1490]
Hello! I am trying to run a simple publisher/subscriber here but everytime I try to call the subscriber for registry, it gives me this:

Subscribing to aeron:udp?endpoint=10.8.1.5:55555 on stream id 1001
Exception in thread "main" java.lang.ExceptionInInitializerError
        at io.aeron.driver.MediaDriver$Context.concludeNullProperties(MediaDriver.java:3574)
        at io.aeron.driver.MediaDriver$Context.conclude(MediaDriver.java:612)
        at io.aeron.driver.MediaDriver.<init>(MediaDriver.java:125)
        at io.aeron.driver.MediaDriver.launch(MediaDriver.java:254)
        at io.aeron.driver.MediaDriver.launchEmbedded(MediaDriver.java:233)
        at io.aeron.driver.MediaDriver.launchEmbedded(MediaDriver.java:212)
        at org.data_cloner.BasicSubscriber.main(BasicSubscriber.java:40)
        at org.data_cloner.BasicPublisher.main(BasicPublisher.java:40)
        at org.data_cloner.Master.main(Master.java:129)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Set sun.nio.ch.SelectorImpl.selectedKeys accessible: module java.base does not "opens sun.nio.ch" to unnamed module @4d4f7787
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at org.agrona.nio.TransportPoller.<clinit>(TransportPoller.java:73)
        ... 9 more

**Comment by PedroMPagani** [comment]
Oops, found this fix on the website, apologies for the issue!

**Comment by chirdeeptomar** [comment]
For people, its here: https://aeroncookbook.com/cookbook-content/aeron-jdk16/
