### ISSUE TITLE
Archive ConductorServiceTimeoutException when using `useConductorAgentInvoker`

### ISSUE THREAD

**Issue by ratcashdev** [real-logic/aeron#1599]
Setting up an Aeron client (1.44.1) instance with `.useConductorAgentInvoker(true)` and pass it to Archive, like:

```java
    Archive.launch(
        new Archive.Context()
            .aeron(aeron)
         ...
         )
```

may results in the following exception:
```
Caused by: io.aeron.exceptions.ConductorServiceTimeoutException: FATAL - service interval exceeded: timeout=10000000000ns, interval=10724637104ns
    at io.aeron.ClientConductor.checkServiceInterval(ClientConductor.java:1455)
    at io.aeron.ClientConductor.checkTimeouts(ClientConductor.java:1439)
    at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:1393)
    at io.aeron.ClientConductor.addCounter(ClientConductor.java:1004)
    at io.aeron.Aeron.addCounter(Aeron.java:519)
    at io.aeron.archive.ArchiveCounters.allocate(ArchiveCounters.java:67)
    at io.aeron.archive.Archive$Context.conclude(Archive.java:1218)
    at io.aeron.archive.Archive.<init>(Archive.java:81)
    at io.aeron.archive.Archive.launch(Archive.java:190)
    ... 50 more
```

**Comment by mikeb01** [comment]
This code doesn't compile.  I.e. you can't pass an `AeronArchive.Context` to the `Archive.launch`.  I've tried replicating the issue, but I'm unable to.  Please could you supply a full example that demonstrates the problem.

**Comment by ratcashdev** [comment]
Apologies, @mikeb01 .
The stack trace was copied, the code not.
```
    at io.aeron.archive.Archive$Context.conclude(Archive.java:1218)
    at io.aeron.archive.Archive.<init>(Archive.java:81)
    at io.aeron.archive.Archive.launch(Archive.java:190)
```

Original post updated

**Comment by mikeb01** [comment]
A complete code example, e.g. a unit test that demonstrates the problem would be appreciated.  The code example above doesn't show the use of `useConductorAgentInvoker(true)`.

**Comment by ratcashdev** [comment]
@mikeb01 will do, just need some more time. Thanks for the patience.

**Comment by mjpt777** [comment]
Closing due to no further activity.
