### ISSUE TITLE
Aeron 1.43.0 - NullPointerException: Cannot invoke "io.aeron.archive.Session.doWork()"

### ISSUE THREAD

**Issue by artem-v** [real-logic/aeron#1611]
Hi 

Aeron 1.43.0

Sometimes (very rarely) NPE happens: 

```
2024-05-02T13:34:37+03:00	java.lang.NullPointerException: Cannot invoke "io.aeron.archive.Session.doWork()" because "session" is null
2024-05-02T13:34:37+03:00		at io.aeron.archive.SessionWorker.doWork(SessionWorker.java:64) ~[aeron-all-1.43.0.jar:1.43.0]
2024-05-02T13:34:37+03:00		at io.aeron.archive.ArchiveConductor.doWork(ArchiveConductor.java:302) ~[aeron-all-1.43.0.jar:1.43.0]
2024-05-02T13:34:37+03:00		at io.aeron.archive.DedicatedModeArchiveConductor.doWork(DedicatedModeArchiveConductor.java:58) ~[aeron-all-1.43.0.jar:1.43.0]
2024-05-02T13:34:37+03:00		at org.agrona.concurrent.AgentRunner.doWork(AgentRunner.java:304) ~[aeron-all-1.43.0.jar:1.43.0]
2024-05-02T13:34:37+03:00		at org.agrona.concurrent.AgentRunner.workLoop(AgentRunner.java:296) ~[aeron-all-1.43.0.jar:1.43.0]
2024-05-02T13:34:37+03:00		at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:162) ~[aeron-all-1.43.0.jar:1.43.0]
2024-05-02T13:34:37+03:00		at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Tried to investigate myself, and with co-workers, but we could not figure out what can cause NPE, hence posting it here.

**Comment by mikeb01** [comment]
Have you tried upgrading to 1.44.1?

**Comment by artem-v** [comment]
> Have you tried upgrading to 1.44.1?

We will upgrade very soon, but currently running on 1.43.0.

**Comment by mikeb01** [comment]
Closing due to inactivity.
