### ISSUE TITLE
An Exception about agrona and reflect when changing java version from 8 to 17

### ISSUE THREAD

**Issue by libliuis** [real-logic/aeron#1613]
Usage:
`
        MediaDriver driver = MediaDriver.launchEmbedded();
`
when I changed Java version from 8 to 17, Aeron reported an Exception about agrona and reflect!
`
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Set sun.nio.ch.SelectorImpl.selectedKeys accessible: module java.base does not "opens sun.nio.ch" to unnamed module @17baae6e
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[na:na]
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[na:na]
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) ~[na:na]
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172) ~[na:na]
	at org.agrona.nio.TransportPoller.<clinit>(TransportPoller.java:73) ~[aeron-all-1.44.1.jar:1.44.1]
`

**Comment by vyazelenko** [comment]
You need to add the following JVM config options when running with `java` executable:
```
--add-opens java.base/sun.nio.ch=ALL-UNNAMED
--add-opens java.base/java.util.zip=ALL-UNNAMED
```

See also https://aeron.io/docs/cookbook-content/aeron-jdk16/.
