### ISSUE TITLE
AeronThroughput DriverTimeoutException: Driver has been inactive for over 10000ms

### ISSUE THREAD

**Issue by huiwang** [real-logic/Aeron#163]
Hello guys, 

I'm trying to launch the AeronThroughput test under intellij/windows but i keep getting the following error ?
I verified that the media driver folder is created successfully. 

```
uk.co.real_logic.aeron.exceptions.DriverTimeoutException: Driver has been inactive for over 10000ms
	at uk.co.real_logic.aeron.ClientConductor.checkDriverHeartbeat(ClientConductor.java:268)
	at uk.co.real_logic.aeron.ClientConductor.onCheckTimeouts(ClientConductor.java:328)
	at uk.co.real_logic.aeron.ClientConductor.doWork(ClientConductor.java:286)
	at uk.co.real_logic.aeron.ClientConductor.doWorkUntil(ClientConductor.java:303)
	at uk.co.real_logic.aeron.ClientConductor.addPublication(ClientConductor.java:125)
	at uk.co.real_logic.aeron.Aeron.addPublication(Aeron.java:118)
	at uk.co.real_logic.aeron.tools.perf_tools.AeronThroughput.main(AeronThroughput.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

***
*** Timeout from the Media Driver - is it currently running? Exiting.
***
```

Can you guys reproduce it on your side ? I don't have much hints on how to get rid of it.

Thanks,
Hui

**Comment by tmontgomery** [comment]
I don't see this on Mac or Linux. I would anticipate that this might be a thread starvation issue, though. So, maybe try it with a Threading model of SHARED (set `aeron.threading.mode` to `SHARED`). Which will lower the throughput, but if the machine can't keep the driver active due to thread oversubscription, then throughput isn't as important.

BTW, aeron-tools are not supported and are going away soon (as in today).

**Comment by tmontgomery** [comment]
One thing to check here is the version of Aeron used by the driver and the clients matches up. Also, if Agrona is in the mix that the right version of Agrona is being used for driver and clients.

**Comment by huiwang** [comment]
The whole module aeron-tools are removed with 5fd276c. I suggest closing this issue.
