### ISSUE TITLE
NPE at `ClusterBackupAgent.reset`

### ISSUE THREAD

**Issue by artem-v** [real-logic/aeron#1652]
Hi

**Aeron 1.44.1**

```
1 observations from 2024-08-22 15:05:16.554+0300 to 2024-08-22 15:05:16.554+0300 for:
io.aeron.cluster.client.ClusterException: WARN - failed to stop log replay
        at io.aeron.cluster.ClusterBackupAgent.reset(ClusterBackupAgent.java:368)
        at io.aeron.cluster.ClusterBackupAgent.resetBackup(ClusterBackupAgent.java:647)
        at io.aeron.cluster.ClusterBackupAgent.doWork(ClusterBackupAgent.java:287)
       ...
Caused by: java.lang.NullPointerException: Cannot invoke "io.aeron.archive.client.AeronArchive.stopReplay(long)" because "this.clusterArchive" is null
        at io.aeron.cluster.ClusterBackupAgent.reset(ClusterBackupAgent.java:364)
        ... 9 more
```

Pretty regularly receiving such error in the counted error log file. Looks like there're conditions on which `clusterArchive` is `null` during `.reset()` call   in  the  `ClusterBackupAgent`.

Unfortunately cannot post clear test that reproduce this.

**Comment by vyazelenko** [comment]
This could happen if ClusterBackup goes through the following state transition `BACKING_UP -> BACKUP_QUERY -> RESET_BACKUP`, i.e. the `ClusterBackup.SourceType` validation failure (e.g. connecting to the leader node while `ClusterBackup.SourceType#FOLLOWER` is used).
I've pushed a fix https://github.com/real-logic/aeron/commit/c37546e2a5134be71d10a77f65cc2f0a975651f8.
