### ISSUE TITLE
IndexOutOfBoundsException logging a REPLICATION_SESSION_STATE_CHANGE event

### ISSUE THREAD

**Issue by ivanbogo** [real-logic/aeron#1693]
With archive logging enabled (i.e. `-Daeron.event.archive.log=all`), we get an `IndexOutOfBoundsException` when the agent tries to log a `REPLICATION_SESSION_STATE_CHANGE` event.
 
Details:
```
[376153.947415680] ARCHIVE: CMD_IN_REPLICATE2 [160/160]: controlSessionId=865114950 correlationId=184 srcRecordingId=1 dstRecordingId=-1 stopPosition=25459136 channelTagId=-1 subscriptionTagId=-1 srcControlStreamId=10 srcControlChannel=aeron:udp?xxx liveDestination= replicationChannel=aeron:udp?xxx:0
[376153.958743157] ARCHIVE: CMD_OUT_RESPONSE [44/44]: controlSessionId=865114950 correlationId=184 relevantId=865114953 code=OK version=68352 errorMessage=
java.lang.IndexOutOfBoundsException: index=3196 length=-1 capacity=8389376
        at org.agrona.AbstractMutableDirectBuffer.boundsCheck0(AbstractMutableDirectBuffer.java:1711)
        at org.agrona.AbstractMutableDirectBuffer.getStringWithoutLengthAscii(AbstractMutableDirectBuffer.java:963)
        at org.agrona.AbstractMutableDirectBuffer.getStringAscii(AbstractMutableDirectBuffer.java:681)
        at io.aeron.agent.ArchiveEventDissector.dissectRecordingSessionStateChange(ArchiveEventDissector.java:561)
        at io.aeron.agent.ArchiveEventCode.lambda$static$8(ArchiveEventCode.java:232)
        at io.aeron.agent.ArchiveEventCode.decode(ArchiveEventCode.java:358)
        at io.aeron.agent.ArchiveComponentLogger.decode(ArchiveComponentLogger.java:61)
        at io.aeron.agent.EventLogReaderAgent.decodeLogEvent(EventLogReaderAgent.java:167)
        at io.aeron.agent.EventLogReaderAgent.onMessage(EventLogReaderAgent.java:144)
        at org.agrona.concurrent.ringbuffer.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:201)
        at io.aeron.agent.EventLogReaderAgent.doWork(EventLogReaderAgent.java:128)
        at org.agrona.concurrent.AgentRunner.doWork(AgentRunner.java:304)
        at org.agrona.concurrent.AgentRunner.workLoop(AgentRunner.java:296)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:162)
        at java.base/java.lang.Thread.run(Thread.java:891)
 
```
 
We managed to trace the issue to `io.aeron.agent.ArchiveEventLogger#logReplicationSessionStateChange` around line 229, where the wrong event type is used.
 
The following patch seems to fix the issue:
 
```
diff --git a/aeron-agent/src/main/java/io/aeron/agent/ArchiveEventLogger.java b/aeron-agent/src/main/java/io/aeron/agent/ArchiveEventLogger.java
--- a/aeron-agent/src/main/java/io/aeron/agent/ArchiveEventLogger.java        (revision de608a4415afff6b15339c0ef7eaf09ad25bc8a6)
+++ b/aeron-agent/src/main/java/io/aeron/agent/ArchiveEventLogger.java     (date 1733313612116)
@@ -226,7 +226,7 @@
         final int captureLength = captureLength(length);
         final int encodedLength = encodedLength(captureLength);
         final ManyToOneRingBuffer ringBuffer = this.ringBuffer;
-        final int index = ringBuffer.tryClaim(RECORDING_SESSION_STATE_CHANGE.toEventCodeId(), encodedLength);
+        final int index = ringBuffer.tryClaim(REPLICATION_SESSION_STATE_CHANGE.toEventCodeId(), encodedLength);
         if (index > 0)
         {
 
```

**Comment by vyazelenko** [comment]
Thanks for reporting. The issue has been fixed in https://github.com/real-logic/aeron/commit/07bafcc4087c6d00a9703c34abf7c33af54ffa4a.
