### ISSUE TITLE
Test MemoryOrderingTest failing

### ISSUE THREAD

**Issue by leigh-perry** [real-logic/Aeron#272]
commit 6982a1d647c1a1980a933c5e928a7d84bbd142e1

Built from Gradle 3.0 under cmd.exe 
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
Windows 10 version 1607 OS Build 14393.82

<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="io.aeron.MemoryOrderingTest" tests="1" skipped="0" failures="1" errors="0" timestamp="2016-08-31T08:39:54" hostname="LPmsi" time="10.013">
  <properties/>
  <testcase name="shouldReceiveMessagesInOrderWithFirstLongWordIntact" classname="io.aeron.MemoryOrderingTest" time="10.013">
    <failure message="org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds" type="org.junit.runners.model.TestTimedOutException">org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
	at io.aeron.MemoryOrderingTest.shouldReceiveMessagesInOrderWithFirstLongWordIntact(MemoryOrderingTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>

**Comment by mjpt777** [comment]
Why build with Gradle 3.0 and not that wrapper? Also can you give the spec for your machine in processors and memory?

**Comment by leigh-perry** [comment]
Mainly to minimise copies of Gradle on my SSD. 
I ran with gradlew, tests passed this time :-)

Laptop
OS Name Microsoft Windows 10 Home
Version 10.0.14393 Build 14393
System Manufacturer Micro-Star International Co., Ltd.
System Model    GT72 2QD
System Type x64-based PC
Processor   Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz, 2601 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date   American Megatrends Inc. E1781IMS.10I, 19/12/2014
SMBIOS Version  2.8
Embedded Controller Version 255.255
BIOS Mode   UEFI
BaseBoard Manufacturer  Micro-Star International Co., Ltd.
BaseBoard Model Not Available
BaseBoard Name  Base Board
Platform Role   Mobile
Secure Boot State   On
PCR7 Configuration  Binding Not Possible
Locale  Australia
Hardware Abstraction Layer  Version = "10.0.14393.0"
Installed Physical Memory (RAM) 32.0 GB
Total Physical Memory   32.0 GB
Available Physical Memory   26.0 GB
Total Virtual Memory    36.7 GB
Available Virtual Memory    29.6 GB
Page File Space 4.75 GB
Page File   C:\pagefile.sys
Hyper-V - VM Monitor Mode Extensions    Yes
Hyper-V - Second Level Address Translation Extensions   Yes
Hyper-V - Virtualization Enabled in Firmware    Yes
Hyper-V - Data Execution Protection Yes

**Comment by mjpt777** [comment]
I'll look into upgrading to Gradle 3.0 and see why it is taking so long. Windows seems to be much slower than Linux for this test anyway. I may need tweak by OS.

**Comment by leigh-perry** [comment]
Thanks for everything Martin.

**Comment by mjpt777** [comment]
I've upgraded to Gradle 3.1 and have it passing on Ubuntu 16.04 and Windows 10.
