### ISSUE TITLE
could not delete file after Publication.close

### ISSUE THREAD

**Issue by patriknw** [real-logic/Aeron#287]
We create a Publication and `offer` some messages, but there is no subscription because the destination node is not started. After 20 seconds we give up and `close` the publication.

When running on Windows the publication logbuffer can't be deleted.

From the media driver error log:
```
IllegalStateException: could not delete file C:\Users\username\AppData\Local\Temp\aeron-username-bluebox-a568d5ff-f0ee-4c85-933e-d64dbf8af902\publications\UDP-00000000-0-7f000001-11065-78FF9606-2-4.logbuffer
    at io.aeron.driver.buffer.MappedRawLog.close(MappedRawLog.java:122)
    at io.aeron.driver.NetworkPublication.close(NetworkPublication.java:172)
    at io.aeron.driver.DriverConductor.onClosePublication(DriverConductor.java:269)
    at io.aeron.driver.cmd.CloseNetworkPublicationCmd.execute(CloseNetworkPublicationCmd.java:32)
    at io.aeron.driver.DriverConductor.onDriverConductorCmd(DriverConductor.java:924)
    at io.aeron.driver.DriverConductor$$Lambda$60/1874641016.accept(Unknown Source)
    at org.agrona.concurrent.OneToOneConcurrentArrayQueue.drain(OneToOneConcurrentArrayQueue.java:106)
    at io.aeron.driver.DriverConductor.doWork(DriverConductor.java:175)
    at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:122)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by patriknw** [comment]
@mbknor I have created this issue for the problem you reported in https://github.com/akka/akka/issues/20623#issuecomment-257564960
Todd and Martin might have some follow up questions for you.

**Comment by mjpt777** [comment]
I found a potential race condition that can happen under CPU resource starvation that I improved with this commit.

https://github.com/real-logic/Aeron/commit/ae359673fe7071c4fcd33c0bdb6299e5a43c80ef

Previous to this we could have released the publication and taken an interrupt or GC pause before lingering the resource. The resource should be lingered before calling the driver which I have done.

**Comment by mjpt777** [comment]
I've put an old laptop under a lot of pressure by having Chrome use a lot of memory and can then get the interservice timeout to occur.
