### ISSUE TITLE
"Unsafe memory access operation in compiled Java code" when using many streams

### ISSUE THREAD

**Issue by svott7** [real-logic/Aeron#290]
Hey,

I receive the following error when I run Aeron with a high number of streams. I tested it with 0.9.9 as well as 1.0.2 on Linux with OpenJDK 1.8.0_91

6 observations from 2016-11-16 10:35:55.143+0100 to 2016-11-16 10:37:30.296+0100 for:
 .lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
	at io.aeron.driver.buffer.MappedRawLog.<init>(MappedRawLog.java:68)
	at io.aeron.driver.buffer.RawLogFactory.newInstance(RawLogFactory.java:114)
	at io.aeron.driver.buffer.RawLogFactory.newNetworkedImage(RawLogFactory.java:84)
	at io.aeron.driver.DriverConductor.newPublicationImageLog(DriverConductor.java:665)
	at io.aeron.driver.DriverConductor.onCreatePublicationImage(DriverConductor.java:228)
	at io.aeron.driver.cmd.CreatePublicationImageCmd.execute(CreatePublicationImageCmd.java:62)
	at io.aeron.driver.DriverConductor.onDriverConductorCmd(DriverConductor.java:922)
	at org.agrona.concurrent.OneToOneConcurrentArrayQueue.drain(OneToOneConcurrentArrayQueue.java:106)
	at io.aeron.driver.DriverConductor.doWork(DriverConductor.java:174)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:106)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mjpt777** [comment]
It is likely you run out of memory and the log file failed to allocate in the storage location. In Aeron 1.0.3 I added a check for sufficient storage for the allocation and a warning when it is running low. If retry with 1.0.4 then you may get a more informative error.

Have you checked for sufficient storage for the number of streams you have connected? `/dev/shm/` on Linux may need to be increased from the default settings for your usecase.
