### ISSUE TITLE
java tests fail

### ISSUE THREAD

**Issue by btorpey** [real-logic/Aeron#30]
Re: #28 

Many thanks -- that does fix the C++ build.

Here's a snip from Java build that is failing:

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldOnlyRemoveSubscriptionMediaEndpointUponRemovalOfAllSubscribers FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:621)
        at org.junit.Assert.assertNotNull(Assert.java:631)
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldOnlyRemoveSubscriptionMediaEndpointUponRemovalOfAllSubscribers(DriverConductorTest.java:287)

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldNotTimeoutSubscriptionOnKeepAlive FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:621)
        at org.junit.Assert.assertNotNull(Assert.java:631)
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldNotTimeoutSubscriptionOnKeepAlive(DriverConductorTest.java:409)

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldKeepSubscriptionMediaEndpointUponRemovalOfAllButOneSubscriber FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertNotNull(Assert.java:621)
        at org.junit.Assert.assertNotNull(Assert.java:631)
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldKeepSubscriptionMediaEndpointUponRemovalOfAllButOneSubscriber(DriverConductorTest.java:262)

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldErrorOnRemoveChannelOnUnknownSessionId FAILED
    Wanted but not invoked:
    senderProxy.newPublication(
        <Capturing argument>
    );
    -> at uk.co.real_logic.aeron.driver.DriverConductorTest.verifySenderNotifiedOfNewPublication(DriverConductorTest.java:471)
    Actually, there were zero interactions with this mock.
        at uk.co.real_logic.aeron.driver.DriverConductorTest.verifySenderNotifiedOfNewPublication(DriverConductorTest.java:471)
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldErrorOnRemoveChannelOnUnknownSessionId(DriverConductorTest.java:313)

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldBeAbleToRemoveMultipleStreams FAILED
    Wanted but not invoked:
    senderProxy.closePublication(<any>);
    -> at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldBeAbleToRemoveMultipleStreams(DriverConductorTest.java:237)
    Actually, there were zero interactions with this mock.
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldBeAbleToRemoveMultipleStreams(DriverConductorTest.java:237)

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldErrorOnRemoveChannelOnUnknownStreamId FAILED
    org.mockito.exceptions.verification.TooManyActualInvocations: 
    eventLogger.logException(<any>);
    Wanted 1 time:
    -> at uk.co.real_logic.aeron.driver.DriverConductorTest.verifyExceptionLogged(DriverConductorTest.java:443)
    But was 2 times. Undesired invocation:
    -> at uk.co.real_logic.aeron.driver.DriverConductor.onClientCommand(DriverConductor.java:324)
        at uk.co.real_logic.aeron.driver.DriverConductorTest.verifyExceptionLogged(DriverConductorTest.java:443)
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldErrorOnRemoveChannelOnUnknownStreamId(DriverConductorTest.java:331)

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldTimeoutSubscription FAILED
    Wanted but not invoked:
    receiverProxy.addSubscription(<any>, 10);
    -> at uk.co.real_logic.aeron.driver.DriverConductorTest.verifyReceiverSubscribes(DriverConductorTest.java:433)
    Actually, there were zero interactions with this mock.
        at uk.co.real_logic.aeron.driver.DriverConductorTest.verifyReceiverSubscribes(DriverConductorTest.java:433)
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldTimeoutSubscription(DriverConductorTest.java:393)

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldNotTimeoutPublicationOnKeepAlive FAILED
    Wanted but not invoked:
    senderProxy.newPublication(
        <Capturing argument>
    );
    -> at uk.co.real_logic.aeron.driver.DriverConductorTest.verifySenderNotifiedOfNewPublication(DriverConductorTest.java:471)
    Actually, there were zero interactions with this mock.
        at uk.co.real_logic.aeron.driver.DriverConductorTest.verifySenderNotifiedOfNewPublication(DriverConductorTest.java:471)
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldNotTimeoutPublicationOnKeepAlive(DriverConductorTest.java:371)

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldBeAbleToAddMultipleStreams FAILED
    Wanted but not invoked:
    senderProxy.newPublication(<any>);
    -> at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldBeAbleToAddMultipleStreams(DriverConductorTest.java:203)
    Actually, there were zero interactions with this mock.
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldBeAbleToAddMultipleStreams(DriverConductorTest.java:203)

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldBeAbleToAddSingleSubscription FAILED
    Wanted but not invoked:
    clientProxy.operationSucceeded(1429);
    -> at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldBeAbleToAddSingleSubscription(DriverConductorTest.java:177)

    However, there were other interactions with this mock:
    -> at uk.co.real_logic.aeron.driver.DriverConductor.onClientCommand(DriverConductor.java:333)
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldBeAbleToAddSingleSubscription(DriverConductorTest.java:177)

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldTimeoutPublication FAILED
    Wanted but not invoked:
    senderProxy.newPublication(
        <Capturing argument>
    );
    -> at uk.co.real_logic.aeron.driver.DriverConductorTest.verifySenderNotifiedOfNewPublication(DriverConductorTest.java:471)
    Actually, there were zero interactions with this mock.
        at uk.co.real_logic.aeron.driver.DriverConductorTest.verifySenderNotifiedOfNewPublication(DriverConductorTest.java:471)
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldTimeoutPublication(DriverConductorTest.java:356)

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldBeAbleToRemoveSingleStream FAILED
    Wanted but not invoked:
    senderProxy.closePublication(<any>);
    -> at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldBeAbleToRemoveSingleStream(DriverConductorTest.java:216)
    Actually, there were zero interactions with this mock.
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldBeAbleToRemoveSingleStream(DriverConductorTest.java:216)

uk.co.real_logic.aeron.driver.DriverConductorTest > shouldBeAbleToAddSinglePublication FAILED
    Wanted but not invoked:
    senderProxy.newPublication(
        <Capturing argument>
    );
    -> at uk.co.real_logic.aeron.driver.DriverConductorTest.verifySenderNotifiedOfNewPublication(DriverConductorTest.java:471)
    Actually, there were zero interactions with this mock.
        at uk.co.real_logic.aeron.driver.DriverConductorTest.verifySenderNotifiedOfNewPublication(DriverConductorTest.java:471)
        at uk.co.real_logic.aeron.driver.DriverConductorTest.shouldBeAbleToAddSinglePublication(DriverConductorTest.java:163)

uk.co.real_logic.aeron.driver.UdpChannelTest > shouldHandleCanonicalFormForMulticastCorrectly SKIPPED

uk.co.real_logic.aeron.driver.UdpChannelTest > shouldParseValidMulticastAddress SKIPPED

uk.co.real_logic.aeron.driver.SelectorAndTransportTest > shouldSendMultipleDataFramesPerDatagramUnicastFromSourceToReceiver FAILED
    java.lang.IllegalStateException: Failed to set SO_RCVBUF: attempted=131072, actual=124928
        at uk.co.real_logic.aeron.driver.UdpChannelTransport.<init>(UdpChannelTransport.java:102)
        at uk.co.real_logic.aeron.driver.ReceiverUdpChannelTransport.<init>(ReceiverUdpChannelTransport.java:58)
        at uk.co.real_logic.aeron.driver.SelectorAndTransportTest.shouldSendMultipleDataFramesPerDatagramUnicastFromSourceToReceiver(SelectorAndTransportTest.java:185)

uk.co.real_logic.aeron.driver.SelectorAndTransportTest > shouldSendEmptyDataFrameUnicastFromSourceToReceiver FAILED
    java.lang.RuntimeException: channel "udp://localhost:40123" : java.net.BindException: Address already in use
        at uk.co.real_logic.aeron.driver.UdpChannelTransport.<init>(UdpChannelTransport.java:112)
        at uk.co.real_logic.aeron.driver.ReceiverUdpChannelTransport.<init>(ReceiverUdpChannelTransport.java:58)
        at uk.co.real_logic.aeron.driver.SelectorAndTransportTest.shouldSendEmptyDataFrameUnicastFromSourceToReceiver(SelectorAndTransportTest.java:135)

        Caused by:
        java.net.BindException: Address already in use
            at sun.nio.ch.Net.bind0(Native Method)
            at sun.nio.ch.Net.bind(Net.java:436)
            at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:706)
            at uk.co.real_logic.aeron.driver.UdpChannelTransport.<init>(UdpChannelTransport.java:77)
            ... 2 more

uk.co.real_logic.aeron.driver.SelectorAndTransportTest > shouldHandleSmFrameFromReceiverToSender FAILED
    java.lang.RuntimeException: channel "udp://localhost:40123" : java.net.BindException: Address already in use
        at uk.co.real_logic.aeron.driver.UdpChannelTransport.<init>(UdpChannelTransport.java:112)
        at uk.co.real_logic.aeron.driver.ReceiverUdpChannelTransport.<init>(ReceiverUdpChannelTransport.java:58)
        at uk.co.real_logic.aeron.driver.SelectorAndTransportTest.shouldHandleSmFrameFromReceiverToSender(SelectorAndTransportTest.java:236)

        Caused by:
        java.net.BindException: Address already in use
            at sun.nio.ch.Net.bind0(Native Method)
            at sun.nio.ch.Net.bind(Net.java:436)
            at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:706)
            at uk.co.real_logic.aeron.driver.UdpChannelTransport.<init>(UdpChannelTransport.java:77)
            ... 2 more

uk.co.real_logic.aeron.driver.SelectorAndTransportTest > shouldHandleBasicSetupAndTeardown FAILED
    java.lang.RuntimeException: channel "udp://localhost:40123" : java.net.BindException: Address already in use
        at uk.co.real_logic.aeron.driver.UdpChannelTransport.<init>(UdpChannelTransport.java:112)
        at uk.co.real_logic.aeron.driver.ReceiverUdpChannelTransport.<init>(ReceiverUdpChannelTransport.java:58)
        at uk.co.real_logic.aeron.driver.SelectorAndTransportTest.shouldHandleBasicSetupAndTeardown(SelectorAndTransportTest.java:103)

        Caused by:
        java.net.BindException: Address already in use
            at sun.nio.ch.Net.bind0(Native Method)
            at sun.nio.ch.Net.bind(Net.java:436)
            at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:706)
            at uk.co.real_logic.aeron.driver.UdpChannelTransport.<init>(UdpChannelTransport.java:77)
            ... 2 more

uk.co.real_logic.aeron.driver.ReceiverTest > shouldNotOverwriteDataFrameWithHeartbeat FAILED
    java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:436)
        at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:706)
        at uk.co.real_logic.aeron.driver.ReceiverTest.setUp(ReceiverTest.java:145)

    java.lang.NullPointerException
        at uk.co.real_logic.aeron.driver.ReceiverTest.tearDown(ReceiverTest.java:160)

uk.co.real_logic.aeron.driver.ReceiverTest > shouldOverwriteHeartbeatWithDataFrame FAILED
    java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:436)
        at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:706)
        at uk.co.real_logic.aeron.driver.ReceiverTest.setUp(ReceiverTest.java:145)

    java.lang.NullPointerException
        at uk.co.real_logic.aeron.driver.ReceiverTest.tearDown(ReceiverTest.java:160)

uk.co.real_logic.aeron.driver.ReceiverTest > shouldHandleNonZeroTermOffsetCorrectly FAILED
    java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:436)
        at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:706)
        at uk.co.real_logic.aeron.driver.ReceiverTest.setUp(ReceiverTest.java:145)

    java.lang.NullPointerException
        at uk.co.real_logic.aeron.driver.ReceiverTest.tearDown(ReceiverTest.java:160)

uk.co.real_logic.aeron.driver.ReceiverTest > shouldInsertDataIntoLogAfterInitialExchange FAILED
    java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:436)
        at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:706)
        at uk.co.real_logic.aeron.driver.ReceiverTest.setUp(ReceiverTest.java:145)

    java.lang.NullPointerException
        at uk.co.real_logic.aeron.driver.ReceiverTest.tearDown(ReceiverTest.java:160)

uk.co.real_logic.aeron.driver.ReceiverTest > shouldCreateRcvTermAndSendSmOnSetup FAILED
    java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:436)
        at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:706)
        at uk.co.real_logic.aeron.driver.ReceiverTest.setUp(ReceiverTest.java:145)

    java.lang.NullPointerException
        at uk.co.real_logic.aeron.driver.ReceiverTest.tearDown(ReceiverTest.java:160)
Results: FAILURE (77 tests, 53 successes, 22 failures, 2 skipped)

77 tests completed, 22 failed, 2 skipped
:aeron-driver:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':aeron-driver:test'.
> There were failing tests. See the report at: file:///shared/Aeron/aeron-driver/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 19.425 secs

**Comment by mjpt777** [comment]
I cannot recreate this on Ubuntu or Fedora so will close for now unless someone care recreate.
