### ISSUE TITLE
NoSuchMethodError while running from scratch

### ISSUE THREAD

**Issue by thhart** [real-logic/Aeron#322]
Hi, I am a newbie testing your library, I downloaded aeron-all 1.2.0 with Maven and I get a strange error when running on top of standard JDK 1.8_121 within Intellij Idea. Do you have an explanation for the error below:

```
Publishing to aeron:udp?endpoint=localhost:40123 on stream Id 10
17-03-03 15:56:36 WARN  (Test.java:124) - java.lang.NoSuchMethodError: org.agrona.IoUtil.mapNewFile(Ljava/io/File;JZ)Ljava/nio/MappedByteBuffer;
java.lang.NoSuchMethodError: org.agrona.IoUtil.mapNewFile(Ljava/io/File;JZ)Ljava/nio/MappedByteBuffer;
	at io.aeron.driver.reports.LossReportUtil.mapLossReport(LossReportUtil.java:50)
	at io.aeron.driver.MediaDriver$Context.conclude(MediaDriver.java:625)
	at io.aeron.driver.MediaDriver.<init>(MediaDriver.java:170)
	at io.aeron.driver.MediaDriver.launch(MediaDriver.java:272)
	at io.aeron.driver.MediaDriver.launchEmbedded(MediaDriver.java:251)
	at io.aeron.driver.MediaDriver.launchEmbedded(MediaDriver.java:231)
	at com.analyticalimaging.uvis.server.Test.lambda$new$0(Test.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by thhart** [comment]
The test is running fine in an isolated environment. I did run within a big project before. It looks like a class version conflict. So will look into myself.
