### ISSUE TITLE
Intermittent Archiver test failure: possible race condition

### ISSUE THREAD

**Issue by mjpt777** [real-logic/Aeron#334]
io.aeron.archiver.ArchiveAndReplaySystemTest > archiveAndReplay STANDARD_ERROR
    Exception in thread "driver-conductor" java.nio.file.FileSystemException: C:\Users\Martin\AppData\Local\Temp\aeron-Martin\publications\UDP-00000000-0-7f000001-54327-1ACDB3D8-65-11.logbuffer: The requested operation cannot be performed on a file with a user-mapped section open.

        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:115)
        at java.nio.channels.FileChannel.open(FileChannel.java:287)
        at java.nio.channels.FileChannel.open(FileChannel.java:335)
        at io.aeron.driver.buffer.MappedRawLog.close(MappedRawLog.java:125)
        at io.aeron.driver.NetworkPublication.close(NetworkPublication.java:207)
        at io.aeron.driver.DriverConductor.onClosePublication(DriverConductor.java:181)
        at io.aeron.driver.cmd.CloseNetworkPublicationCmd.execute(CloseNetworkPublicationCmd.java:32)
        at io.aeron.driver.DriverConductor.onDriverConductorCmd(DriverConductor.java:1014)
        at org.agrona.concurrent.OneToOneConcurrentArrayQueue.drain(OneToOneConcurrentArrayQueue.java:106)
        at io.aeron.driver.DriverConductor.doWork(DriverConductor.java:153)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:122)
        at java.lang.Thread.run(Thread.java:745)
    io.aeron.exceptions.DriverTimeoutException: MediaDriver has been inactive for over 10000ms
        at io.aeron.ClientConductor.checkDriverHeartbeat(ClientConductor.java:531)
        at io.aeron.ClientConductor.onCheckTimeouts(ClientConductor.java:495)
        at io.aeron.ClientConductor.doWork(ClientConductor.java:421)
        at io.aeron.ClientConductor.doWork(ClientConductor.java:138)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:122)
        at java.lang.Thread.run(Thread.java:745)

**Comment by pwebbitrs** [comment]
FYI.   We are also noticing this occuring intermittently.   Do you know the cause or any work arounds at this stage?   

```
2017-04-20 09:25:23.464 ERROR [AeronErrorLog                             ] -  Aeron error: 1 observations from 2017-04-20 09:25:20.474+0200 to 2017-04-20 09:25:20.474+0200 for: java.nio.file.FileSystemException: C:\QA\source\local\data\node\transport\publications\UDP-00000000-0-7f000001-5555-C71ABA3B-5-4.logbuffer: The requested operation cannot be performed on a file with a user-mapped section open.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newFileChannel(WindowsFileSystemProvider.java:115)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at io.aeron.driver.buffer.MappedRawLog.close(MappedRawLog.java:125)
	at io.aeron.driver.NetworkPublication.close(NetworkPublication.java:207)
	at io.aeron.driver.DriverConductor.onClosePublication(DriverConductor.java:181)
	at io.aeron.driver.cmd.CloseNetworkPublicationCmd.execute(CloseNetworkPublicationCmd.java:32)
	at io.aeron.driver.DriverConductor.onDriverConductorCmd(DriverConductor.java:1014)
	at io.aeron.driver.DriverConductor$$Lambda$21/1352946830.accept(Unknown Source)
	at org.agrona.concurrent.OneToOneConcurrentArrayQueue.drain(OneToOneConcurrentArrayQueue.java:106)
	at io.aeron.driver.DriverConductor.doWork(DriverConductor.java:153)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:122)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mjpt777** [comment]
@pwebbitrs  Was it the same test?

**Comment by mjpt777** [comment]
@pwebbitrs On looking at that stack trace it seems not to be related to this issue but another one. My guess would be you have a timeout out client that the driver is cleaning up but it still has logs. I've seen this happen with long GC pauses (> 5 sec) or when running the client in a debugger.

**Comment by mjpt777** [comment]
I'm closing this for now with the changes I've made to the archiver so that future issues should be more specific.
