### ISSUE TITLE
io.aeron.exceptions.RegistrationException: Encoded string larger than maximum size: 124

### ISSUE THREAD

**Issue by sturgeda** [real-logic/Aeron#335]
When adding a subscription/publication, our channel url now hits the size limit of 124 bytes

aeron:udp?endpoint=XXX.XXX.XX.XXX:XXXXX|interface=XX.XX.XXX.X/24|ttl=32|appName=XXXXXXXXXXXXXX|..

The error is generated from within the media driver when setting the label for a counter :

	  at org.agrona.concurrent.UnsafeBuffer.putStringUtf8(UnsafeBuffer.java:1207)
	  at org.agrona.concurrent.status.CountersManager.allocate(CountersManager.java:141)
	  at org.agrona.concurrent.status.CountersManager.newCounter(CountersManager.java:170)
	  at io.aeron.driver.status.ChannelEndpointStatus.allocate(ChannelEndpointStatus.java:110)
	  at io.aeron.driver.status.ReceiveChannelStatus.allocate(ReceiveChannelStatus.java:40)
	  at io.aeron.driver.DriverConductor.getOrCreateReceiveChannelEndpoint(DriverConductor.java:913)
	  at io.aeron.driver.DriverConductor.onAddNetworkSubscription(DriverConductor.java:551)
	  at io.aeron.driver.ClientListenerAdapter.onMessage(ClientListenerAdapter.java:133)
	  at org.agrona.concurrent.ringbuffer.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:158)
	  at io.aeron.driver.ClientListenerAdapter.receive(ClientListenerAdapter.java:68)
	  at io.aeron.driver.DriverConductor.doWork(DriverConductor.java:148)
	  at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:122)
	  at java.lang.Thread.run(Thread.java:745)

Are we able to increase the limit to something like 256 bytes ?

Thanks

Dave

**Comment by mjpt777** [comment]
This has been increased to 380 in Aeron 1.2.4.

**Comment by sturgeda** [comment]
Yep ok. we're on 1.2.3. We shall upgrade. Thanks for the quick response !
