### ISSUE TITLE
ConductorServiceTimeoutException

### ISSUE THREAD

**Issue by pingvasanth** [real-logic/aeron#374]
we have three servers creating publication to one subscription server 
On the publisher we seeing below logs 

2017-07-12 21:38:58,993  INFO aeron-client-conductor  Image Unavailable:io.aeron.Image@26d4fb20 session -1939625920
2017-07-12 21:38:58,993  INFO aeron-client-conductor  Image Unavailable :io.aeron.Image@39b5cc72 session 1901581560
2017-07-12 21:38:58,993  INFO aeron-client-conductor new  Image Unavailable :io.aeron.Image@659e0d43 session -1535749004
io.aeron.exceptions.ConductorServiceTimeoutException: Timeout between service calls over 5000000000ns
        at io.aeron.ClientConductor.onCheckTimeouts(ClientConductor.java:508)
        at io.aeron.ClientConductor.doWork(ClientConductor.java:431)
        at io.aeron.ClientConductor.doWork(ClientConductor.java:143)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:140)
        at java.lang.Thread.run(Thread.java:745)

On the subscriber, we see
subscriber 1
2017-07-12 21:39:13,483 ERROR aeron-client-conductor Image Unavailable :1901581559

subscriber 2
2017-07-12 21:39:14,274 ERROR aeron-client-conductor Image Unavailable :1901581558

subscriber 3
2017-07-12 21:39:13,779 ERROR aeron-client-conductor Image Unavailable :1901581561

Once we get the image unavailable, we clear and close the publication. then we try to create new publication, but we still getting same publication from the api "Aeron.addPublication" which is closed.

Could you help us how to get new publication.

**Comment by mjpt777** [comment]
An interservice timeout indicates very long GC pauses or resource starvation on the machine which is not a situation to be in for low-latency applications.

Can you provide more information on what Aeron version, JDK, and OS you are using?

When this happens it is useful to run AeronStat to get a view of the counters on each machine?

**Comment by mjpt777** [comment]
After a ConductorServiceTimeoutException you will need to close the Aeron client and reconnect.

**Comment by pingvasanth** [comment]
Thanks Martin, actually we doing functional testing and got into this issue .. seems our functional testing servers are slow.
We using aeron 1.3, JDK 8, and CentOS release 6.6
Thanks for the input, we implementing reconnect mechanism too.
