### ISSUE TITLE
C++ exception with description "Negative size" thrown

### ISSUE THREAD

**Issue by bedding** [real-logic/aeron#388]
I started the media driver with IPC term buffer size set to 1GB,

```-Daeron.ipc.term.buffer.length=1073741824)```

I am able to add publication, but when I call ```findPublication``` my application always threw the exception with description "Negative size".

Everything worked fine if IPC term buffer size is something less than 1GB. What could cause this problem?

**Comment by tmontgomery** [comment]
This is Java media driver, correct?

FYI, C++ `addPublication` is asynchronous. Any errors will come through `findPublication`.

**Comment by tmontgomery** [comment]
BTW, what is the error in the `ErrorLog`?

**Comment by bedding** [comment]
Yes it is Java media driver. Following is from the error log,

```
***
1 observations from 2017-08-21 21:30:42.287+0000 to 2017-08-21 21:30:42.287+0000 for:
 java.lang.IllegalArgumentException: Negative size
        at sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:865)
        at io.aeron.driver.buffer.MappedRawLog.<init>(MappedRawLog.java:63)
        at io.aeron.driver.buffer.RawLogFactory.newInstance(RawLogFactory.java:154)
        at io.aeron.driver.buffer.RawLogFactory.newIpcPublication(RawLogFactory.java:124)
        at io.aeron.driver.DriverConductor.newIpcPublicationLog(DriverConductor.java:798)
        at io.aeron.driver.DriverConductor.addIpcPublication(DriverConductor.java:1038)
        at io.aeron.driver.DriverConductor.getOrAddIpcPublication(DriverConductor.java:1025)
        at io.aeron.driver.DriverConductor.onAddIpcPublication(DriverConductor.java:506)
        at io.aeron.driver.DriverAdapter.addPublication(DriverAdapter.java:198)
        at io.aeron.driver.DriverAdapter.onMessage(DriverAdapter.java:89)
        at org.agrona.concurrent.ringbuffer.ManyToOneRingBuffer.read(ManyToOneRingBuffer.java:158)
        at io.aeron.driver.DriverAdapter.receive(DriverAdapter.java:68)
        at io.aeron.driver.DriverConductor.doWork(DriverConductor.java:146)
        at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:79)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:140)
        at java.lang.Thread.run(Thread.java:748)


1 distinct errors observed.
```

**Comment by tmontgomery** [comment]
Ah. That helps. Thanks. Let me look at it.

**Comment by tmontgomery** [comment]
I've made 2 changes. One to the Java Media Driver and the other to the C++ API. These seem to work for me. But not doing any real tests besides `BasicSubscriber` and `BasicPublisher`.
