### ISSUE TITLE
Aeron Client crashes in case of PC clock update

### ISSUE THREAD

**Issue by artyomkorzun** [real-logic/aeron#392]
**Application:** java app with Aeron 1.3.0 (client + embedded driver).
**OS:** CentOS 6+.

**Steps:**
1.  PC clock is 2 minutes behind.
2.  Update PC clock.
3.  Aeron Client crashes.
     
**Exception:** io.aeron.exceptions.DriverTimeoutException: Driver has been inactive for over 10000ms
         at io.aeron.ClientConductor.checkDriverHeartbeat(ClientConductor.java:338)
         at io.aeron.ClientConductor.onCheckTimeouts(ClientConductor.java:411)
         at io.aeron.ClientConductor.doWork(ClientConductor.java:356)
         at io.aeron.ClientConductor.doWork(ClientConductor.java:133)
         at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:122)
         at org.thread.affinity.PinnedRunnable.run(PinnedRunnable.java:27)
         at java.lang.Thread.run(Thread.java:745)

Is it still actual for 1.4.1?

**Comment by mjpt777** [comment]
Aeron is designed to be a high performance messaging system with round trips are typically measured in microseconds. We need to detect dead clients so they can be unblocked, thus allowing others to make progress, and we do this with timeouts. One such timeout is the inter-service-timeout which has been triggered here. The exception you see is Aeron doing what it is expected to do. It has not crashed. It has thrown an exception indicating that the conditions it is expecting are not being meet.

If you are designing a system for performance why have a clock drifting so far from the actual time? Such a large clock adjustment will result in timeouts being triggered an any system that uses intervals smaller than the likely clock adjustments.
