### ISSUE TITLE
ArchiveTest.recordAndReplayExclusivePublication Failed

### ISSUE THREAD

**Issue by mjpt777** [real-logic/aeron#409]
io.aeron.archive.ArchiveTest > recordAndReplayExclusivePublication[threading modes: driver=SHARED archive=SHARED] STANDARD_ERROR
    io.aeron.archive.ArchiveTest failed with random seed: 422830290689147

io.aeron.archive.ArchiveTest > recordAndReplayExclusivePublication[threading modes: driver=SHARED archive=SHARED] FAILED
    java.lang.AssertionError:
    Expected: is <2148>
         but: was <2149>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at io.aeron.archive.ArchiveTest.validateFragment1(ArchiveTest.java:624)
        at io.aeron.archive.RecordingFragmentReader.controlledPoll(RecordingFragmentReader.java:191)
        at io.aeron.archive.ArchiveTest.validateArchiveFile(ArchiveTest.java:599)
        at io.aeron.archive.ArchiveTest.postPublicationValidations(ArchiveTest.java:362)
        at io.aeron.archive.ArchiveTest.recordAndReplayExclusivePublication(ArchiveTest.java:206)

**Comment by mjpt777** [comment]
This failure can be replicated if the seed is set in the test to : 422830290689147.

**Comment by mjpt777** [comment]
Turns out the test has invalid assumptions. The above seed will have 320 remaining in the starting term and the first message ends up being 874 bytes and does not fit so a padding record is inserted and the term is rotated thus the actual `termId` is one greater than the expected.
