### ISSUE TITLE
PubAndSubTest > shouldFragmentExactMessageLengthsCorrectly FAILED

### ISSUE THREAD

**Issue by mjpt777** [real-logic/aeron#410]
Potential race in test case. Was seen by another use when switching from dedicated to shared threading mode.

io.aeron.PubAndSubTest > shouldFragmentExactMessageLengthsCorrectly FAILED
    org.junit.experimental.theories.internal.ParameterizedAssertionError: shouldFragmentExactMessageLengthsCorrectly("aeron:udp?endpoint=localhost:54325" <from UNICAST_URI>)

        Caused by:
        io.aeron.exceptions.RegistrationException: RuntimeException : Channel error: Address already in use: bind : aeron:udp?endpoint=localhost:54325
            at io.aeron.ClientConductor.onError(ClientConductor.java:273)
            at io.aeron.DriverEventsAdapter.onMessage(DriverEventsAdapter.java:73)
            at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:100)
            at io.aeron.DriverEventsAdapter.receive(DriverEventsAdapter.java:53)
            at io.aeron.ClientConductor.service(ClientConductor.java:432)
            at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:468)
            at io.aeron.ClientConductor.addSubscription(ClientConductor.java:238)
            at io.aeron.ClientConductor.addSubscription(ClientConductor.java:221)
            at io.aeron.Aeron.addSubscription(Aeron.java:278)
            at io.aeron.PubAndSubTest.launch(PubAndSubTest.java:96)
            at io.aeron.PubAndSubTest.shouldFragmentExactMessageLengthsCorrectly(PubAndSubTest.java:807)

**Comment by mjpt777** [comment]
Failed due to another instance running at the same time.
