### ISSUE TITLE
C++Media Driver with java client

### ISSUE THREAD

**Issue by rayqi36** [real-logic/aeron#431]
It seems that while I running a Cpp Driver , I could not use java client to pub and sub. When I start the java program , it would throw a exception like this
LogFileName is /dev/shm/aeron-root/publications/UDP-00000000-0-0a027556-40124-79d1f3f7-a-f.logbuffer
LogFileSize is 805306816
TERM_MIN_LENGTH is 65536 and termLength is 0
java.lang.IllegalStateException: Term length less than min length of 65536: length=0
	at io.aeron.logbuffer.LogBufferDescriptor.checkTermLength(LogBufferDescriptor.java:225)
	at io.aeron.LogBuffers.<init>(LogBuffers.java:68)
	at io.aeron.MappedLogBuffersFactory.map(MappedLogBuffersFactory.java:25)
	at io.aeron.ClientConductor.logBuffers(ClientConductor.java:416)
	at io.aeron.ClientConductor.onNewPublication(ClientConductor.java:290)
	at io.aeron.DriverEventsAdapter.onMessage(DriverEventsAdapter.java:102)
	at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:100)
	at io.aeron.DriverEventsAdapter.receive(DriverEventsAdapter.java:53)
	at io.aeron.ClientConductor.service(ClientConductor.java:432)
	at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:468)
	at io.aeron.ClientConductor.addPublication(ClientConductor.java:169)
	at io.aeron.Aeron.addPublication(Aeron.java:235)
	at io.aeron.samples.Pong.main(Pong.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:745)
[WARNING] 
java.lang.IllegalStateException: Term length less than min length of 65536: length=0
	at io.aeron.logbuffer.LogBufferDescriptor.checkTermLength(LogBufferDescriptor.java:225)
	at io.aeron.LogBuffers.<init>(LogBuffers.java:68)
	at io.aeron.MappedLogBuffersFactory.map(MappedLogBuffersFactory.java:25)
	at io.aeron.ClientConductor.logBuffers(ClientConductor.java:416)
	at io.aeron.ClientConductor.onNewPublication(ClientConductor.java:290)
	at io.aeron.DriverEventsAdapter.onMessage(DriverEventsAdapter.java:102)
	at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:100)
	at io.aeron.DriverEventsAdapter.receive(DriverEventsAdapter.java:53)
	at io.aeron.ClientConductor.service(ClientConductor.java:432)
	at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:468)
	at io.aeron.ClientConductor.addPublication(ClientConductor.java:169)
	at io.aeron.Aeron.addPublication(Aeron.java:235)
	at io.aeron.samples.Pong.main(Pong.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:745)

**Comment by tmontgomery** [comment]
What version are you using?

**Comment by rayqi36** [comment]
1.5.0-SNAPSHOT,maybe it is not a stable version ?

**Comment by tmontgomery** [comment]
Try the 1.5.2 release tag.

**Comment by mjpt777** [comment]
Is this still an issue with 1.7.0?

**Comment by rayqi36** [comment]
Sorry, late to close this issue.  I'm now using the version 1.6.0, it works good with the cpp dirver and java client.
