### ISSUE TITLE
Need to close a Publication on channel conflict

### ISSUE THREAD

**Issue by mjpt777** [real-logic/aeron#456]
If a port conflict, or the like, occurs when a publication is set up with a clashing channel then it gets a repeated error while trying to send a setup message as below. We need a means of cleaning up channels and their associated publications and subscriptions when socket errors occur.

```
java.nio.channels.NotYetConnectedException
	at sun.nio.ch.DatagramChannelImpl.write(DatagramChannelImpl.java:596)
	at io.aeron.driver.media.SendChannelEndpoint.send(SendChannelEndpoint.java:195)
	at io.aeron.driver.NetworkPublication.setupMessageCheck(NetworkPublication.java:534)
	at io.aeron.driver.NetworkPublication.send(NetworkPublication.java:245)
	at io.aeron.driver.Sender.doSend(Sender.java:163)
	at io.aeron.driver.Sender.doWork(Sender.java:89)
	at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:233)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:159)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tmontgomery** [comment]
The `NotYetConnectedException` is the result of trying to send after a conflict on the publication side. This can also happen if the OS hasn't been connected for a couple reasons. So, we can't simply stop on this particular exception as it can be spurious.

However, this particular exception should be caught and ignored on sending.

**Comment by tmontgomery** [comment]
Some now handled by 1b437856fa405c4921b0f35f7fdabdea3fc7de7f to reduce number of exceptions.

**Comment by tmontgomery** [comment]
In addition, we should add in a force close command response so that a Publication/Subscription/Counter can be forcibly closed by the driver and the client informed. In addition, this response could be used to inform the client of a driver being shutdown.
