### ISSUE TITLE
 Encoded message exceeds maxMessageLength of 2097152

### ISSUE THREAD

**Issue by bjlgcxc** [real-logic/aeron#473]
java.lang.RuntimeException: java.lang.IllegalArgumentException: Encoded message exceeds maxMessageLength of 2097152, length=4724678

Caused by: java.lang.IllegalArgumentException: Encoded message exceeds maxMessageLength of 2097152, length=4724678
        at io.aeron.Publication.checkForMaxMessageLength(Publication.java:467)
        at io.aeron.Publication.offer(Publication.java:333)
        at io.aeron.Publication.offer(Publication.java:298)
        at io.aeron.Publication.offer(Publication.java:284)

 how can I config the maxMessageLength to larger size ?

**Comment by mjpt777** [comment]
You can increase the length of the term buffer but this is ultimately limited to 16MB maximum for Aeron. However really large messages are a design smell. It is better to break up you message into chunks for transmission.
