### ISSUE TITLE
Getting error when trying to use Multi-Destination-Cast

### ISSUE THREAD

**Issue by davidt922** [real-logic/aeron#488]
I am trying to use the Multi-Destination-Cast transportation, but I dont know how to configure-it, I am trying to implement the Example URIs explained here using the SimplePublisher.java and the SimpleSubscriber.java.

I have one publisher and two subscribers.

Using SimplePublisher.java and SimpleSubscriber.java, I've only changed:

- From SimplePublisher.java

`final String channel = "aeron:udp?control=192.168.0.3:4050|control-mode=manual";`
And From SimpleSubscriber.java:

I have duplicated the class SimpleSubcriber1.java and SimpleSubcriber2.java and I have changed the following configuration:

SimpleSubcriber1:

`final String channel = "aeron:udp?endpoint=192.168.0.4:4051"`
and

SimpleSubcriber2:

`final String channel = "aeron:udp?endpoint=192.168.0.5:4052"`
The errors that I get for both the publisher and the subcriber are almost identical:

For the Publisher:

```
Publishing to aeron:udp?control=192.168.0.3:4050|control-mode=manual on stream Id 10
io.aeron.exceptions.ChannelEndpointException: RuntimeException : Channel error: Cannot assign requested address: bind : aeron:udp?control=192.168.0.3:4050|control-mode=manual
at io.aeron.ClientConductor.onChannelEndpointError(ClientConductor.java:196)
at io.aeron.DriverEventsAdapter.onMessage(DriverEventsAdapter.java:77)
at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:100)
at io.aeron.DriverEventsAdapter.receive(DriverEventsAdapter.java:56)
at io.aeron.ClientConductor.service(ClientConductor.java:660)
at io.aeron.ClientConductor.doWork(ClientConductor.java:151)
at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:233)
at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:159)
at java.lang.Thread.run(Thread.java:748)
Failed to connect to subscriber
```

And, for the subcriber:

```
Subscribing to aeron:udp?endpoint=192.168.0.4:4051 on stream Id 10
io.aeron.exceptions.ChannelEndpointException: RuntimeException : Channel error: Cannot assign requested address: bind : aeron:udp?endpoint=192.168.0.4:4051
at io.aeron.ClientConductor.onChannelEndpointError(ClientConductor.java:187)
at io.aeron.DriverEventsAdapter.onMessage(DriverEventsAdapter.java:77)
at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:100)
at io.aeron.DriverEventsAdapter.receive(DriverEventsAdapter.java:56)
at io.aeron.ClientConductor.service(ClientConductor.java:660)
at io.aeron.ClientConductor.doWork(ClientConductor.java:151)
at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:233)
at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:159)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by tmontgomery** [comment]
From the exceptions, UDP port 4050 and port 4051 on IP 192.168.0.3 and 192.168.0.4 are not assignable. Make sure Subscriber2 is actually on IP 192.168.0.5 and has nothing else bound to that port. Same with Publisher, etc.

**Comment by davidt922** [comment]
Sorry, i'm quite new with this library, the ip have to be my machine ip, so 'localhost' if both subcribers and the publisher are on the same machine?

**Comment by tmontgomery** [comment]
For MDC, the publisher "control" is the local IP and port (or can be localhost, but then traffic is limited to the local machine). The subscription "endpoint" is the local IP (to the subscription) and port. As you are doing a manual MDC, you need to use `Publication.addDestination` for each subscription.

**Comment by davidt922** [comment]
100% Working, Thank you very much @tmontgomery

**Comment by tmontgomery** [comment]
Glad it's working.
