### ISSUE TITLE
JVM crash when driver times out

### ISSUE THREAD

**Issue by mattgodbolt** [real-logic/aeron#539]
I've experienced a number of JVM crashes when single stepping. My setup is:

* Java media driver (in process)
* Java receiver
* C++ separate process sender
* Using IPC

If I breakpoint in the java side, the C++ code understandably times out and detaches from the media driver.

The java code dies:

```
**#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f44159c4c07, pid=5265, tid=0x00007f43c73fa700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0xa9dc07]  Unsafe_GetShort+0x47**
```

Sometimes I get a bit of stack in the death throes:

```
**# Problematic frame:
# V  [libjvm.so+0xa9dc07]    at io.aeron.ClientConductor.checkServiceInterval(ClientConductor.java:745)
    at io.aeron.ClientConductor.onCheckTimeouts(ClientConductor.java:720)
    at io.aeron.ClientConductor.service(ClientConductor.java:659)
    at io.aeron.ClientConductor.doWork(ClientConductor.java:151)
    at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:268)
    at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:161)
    at java.lang.Thread.run(Thread.java:748)
io.aeron.exceptions.ConductorServiceTimeoutException: Exceeded (ns): 5000000000
    at io.aeron.ClientConductor.checkServiceInterval(ClientConductor.java:745)
    at io.aeron.ClientConductor.onCheckTimeouts(ClientConductor.java:720)
    at io.aeron.ClientConductor.service(ClientConductor.java:659)
    at io.aeron.ClientConductor.doWork(ClientConductor.java:151)
    at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:268)
    at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:161)
    at java.lang.Thread.run(Thread.java:748)
  Unsafe_GetShort+0x47**
```

this is using aeron v1.9.3 on the Java side.

**Comment by nitsanw** [comment]
IME this can happen due to IDE trying to call .toString on objects at a bad
time.

**Comment by mjpt777** [comment]
@nitsanw Is this any specific object types?

**Comment by nitsanw** [comment]
@mjpt777 this is due to IDE calling toString so it can show you values in the "variables" window. I've seen it before in cases where the resource being used in the toString method is no longer valid, e.g. where the getShort above would be using some offset into a buffer that has been released.

**Comment by mjpt777** [comment]
@mattgodbolt Is this happening in the client or driver process?

**Comment by mattgodbolt** [comment]
Hi @mjpt777 sorry for the late reply. I'm using an embedded driver so I can't easily tell. I'm debugging the client though.

**Comment by mjpt777** [comment]
With the latest version the linger timeout on resources is configurable in the Java client. You can set this figure high for debugging. https://github.com/real-logic/aeron/commit/ac2847d7f6275260d60fa4cc1e85c90c3e89ba77
