### ISSUE TITLE
Exception setting cluster time

### ISSUE THREAD

**Issue by epickrram** [real-logic/aeron#576]
Not easily reproducible I'm afraid, but looks as though a schedule timer message was received on the ConsensusModuleAdapter *before* the time was set by an incoming application/lifecycle message.

```
java.lang.IllegalStateException: can not set startTime with active timers
  at org.agrona.DeadlineTimerWheel.resetStartTime(DeadlineTimerWheel.java:190)
  at io.aeron.cluster.TimerService.resetStartTime(TimerService.java:66)
  at io.aeron.cluster.ConsensusModuleAgent.clusterTimeMs(ConsensusModuleAgent.java:2349)
  at io.aeron.cluster.ConsensusModuleAgent.doWork(ConsensusModuleAgent.java:261)
  at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:268)
  at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:161)
  at java.lang.Thread.run(Thread.java:748)
```

I came across this by chance, so not really sure of what set of steps got the system into this state.

**Comment by epickrram** [comment]
Could this be a problem with a Timer being hydrated from the snapshot:

https://github.com/real-logic/aeron/blob/master/aeron-cluster/src/main/java/io/aeron/cluster/ConsensusModuleSnapshotLoader.java#L122

Presumably the snapshot needs to be loaded before replay can begin, and it seems as though the replay messages/ConsensusModuleAgent dury cycle are responsible for setting cluster time. If that's the case, then the timer will be added to the TimerService before its current time has been set.

**Comment by epickrram** [comment]
@JPWatson has pointed out that we're scheduling a timer in `ClusteredService.onStart`, which I guess isn't the correct time. Will fix that up and keep an eye on the logs.
