### ISSUE TITLE
[Archive/Java] Reffering channel with tags doesn't work in Archive

### ISSUE THREAD

**Issue by QIvan** [real-logic/aeron#591]
Hi! According to Martin's proposal to use tags in my scenario I wrote a test method in `io.aeron.archive.BasicArchiveTest`: 

```java

    @Test
    public void archiveTags() {

        String tags = "123";
        String channelWithEndpointAndTags = new ChannelUriStringBuilder()
                .media("udp")
                .endpoint("localhost:54325")
                .tags(tags)
                .build();
        String channelWithTagsOnly = new ChannelUriStringBuilder()
                .media("udp")
                .tags(tags)
                .build();

        aeronArchive.startRecording(channelWithEndpointAndTags, RECORDING_STREAM_ID, LOCAL);

        final String messagePrefix = "Message-Prefix-";
        try (Publication publication = aeron.addPublication(channelWithEndpointAndTags, RECORDING_STREAM_ID);
                Subscription subscription = aeron.addSubscription(channelWithEndpointAndTags, RECORDING_STREAM_ID);) {

            offer(publication, 1, messagePrefix);
            consume(subscription, 1, messagePrefix);
        }

        final MutableBoolean channelExists = new MutableBoolean(false);

        aeronArchive.listRecordingsForUri(
                0,
                Integer.MAX_VALUE,
//                channelWithEndpointAndTags,           //   (1)
                channelWithTagsOnly,                           //    (2)
                RECORDING_STREAM_ID,
                (controlSessionId, correlationId, recordingId, startTimestamp, stopTimestamp,
                        startPosition, stopPosition, initialTermId, segmentFileLength,
                        termBufferLength, mtuLength, sessionId, streamId, strippedChannel,
                        originalChannel, sourceIdentity) -> {

                    channelExists.set(true);

                });

        assertTrue(channelExists.get());
    }

```
And it fails. But if we use the line `(1)` instead of `(2)` The test is ok.  

Did I understand wrong this part of the [doc](https://github.com/real-logic/aeron/wiki/Multiple-Destinations#tags)
> The channel may be referenced by tag of 1001 without needing to specify the endpoint.
> ``` aeron:udp?tags=1001```

A little remember about the conversation in gitter: 

Ivan Zemlyanskiy @QIvan Nov 28 02:49
Hi everyone
i've been wondering It'd be nice for my use-cases if Archive recordings are able to have an alias and there is a method AeronArchive#listRecordingsForAlias which works the same way as AeronArchive#listRecordingsForUri but instead a channel you put your name for a stream.
I'd like to hear what the community thinks about it. Will it useful/convenient for you or you're fine with the current API?
Thanks!

Martin Thompson @mjpt777 Nov 28 10:48
@QIvan could you give an example of how you would see that working from an API perspective?

Ivan Zemlyanskiy @QIvan Nov 28 12:43
assume we have 2 additional methods in AeronArchive
```java
public long startRecordingWithAlias(
            final String alias,
            final String channel, 
            final int streamId,
            final SourceLocation sourceLocation)
```
and
```java
public int listRecordingsForAlias(
            final String alias,
            final long fromRecordingId,
            final int recordCount,
            final RecordingDescriptorConsumer consumer)
```
and usage something like this:
```java
final long subscriptionId = aeronArchive.startRecordingWithAlias("my-stream", RECORDING_CHANNEL, RECORDING_STREAM_ID, LOCAL);

publishSomethingInMyStream();

aeronArchive.listRecordingsForAlias("my-stream", 0, Integer.MAX_VALUE, someConsumerForMyStream);
```
Martin Thompson @mjpt777 Nov 28 12:49
@QIvan Could you possibly use tags for this? https://github.com/real-logic/aeron/wiki/Multiple-Destinations#tags

Ivan Zemlyanskiy @QIvan Nov 28 12:54
wow... yes i'll check. Thank you for the link i didn't notice this feature in the doc before (but i thought i've read all)...
My apologies.

**Comment by mjpt777** [comment]
For the `listRecordingsForUri` operation, the channel you pass is used for a String contains operation for the original URI. Try with just `tags=123`, rather than the full URI.

**Comment by QIvan** [comment]
for `tags=123`

```
java.lang.IllegalArgumentException: Aeron URIs must start with 'aeron:', found: 'tags=123'
	at io.aeron.ChannelUri.parse(ChannelUri.java:314)
	at io.aeron.archive.ArchiveConductor.newListRecordingsForUriSession(ArchiveConductor.java:332)
	at io.aeron.archive.ControlSession.onListRecordingsForUri(ControlSession.java:148)
	at io.aeron.archive.ControlSessionDemuxer.onListRecordingsForUri(ControlSessionDemuxer.java:158)
	at io.aeron.archive.ControlRequestAdapter.onFragment(ControlRequestAdapter.java:163)
	at io.aeron.ImageFragmentAssembler.onFragment(ImageFragmentAssembler.java:109)
	at io.aeron.logbuffer.TermReader.read(TermReader.java:77)
	at io.aeron.Image.poll(Image.java:294)
	at io.aeron.archive.ControlSessionDemuxer.doWork(ControlSessionDemuxer.java:83)
	at io.aeron.archive.SessionWorker.doWork(SessionWorker.java:56)
	at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:268)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:161)
	at java.lang.Thread.run(Thread.java:748)

io.aeron.exceptions.TimeoutException: awaiting recording descriptors - correlationId=19
	at io.aeron.archive.client.AeronArchive.checkDeadline(AeronArchive.java:948)
	at io.aeron.archive.client.AeronArchive.pollForDescriptors(AeronArchive.java:1097)
	at io.aeron.archive.client.AeronArchive.listRecordingsForUri(AeronArchive.java:792)
	at io.aeron.archive.BasicArchiveTest.archiveTags(BasicArchiveTest.java:154)
```

<br/>
<br/>

and for `aeron:tags=123`
```
java.lang.IllegalArgumentException: invalid media: tags=123
	at io.aeron.ChannelUriStringBuilder.media(ChannelUriStringBuilder.java:159)
	at io.aeron.archive.ArchiveConductor.strippedChannelBuilder(ArchiveConductor.java:696)
	at io.aeron.archive.ArchiveConductor.newListRecordingsForUriSession(ArchiveConductor.java:332)
	at io.aeron.archive.ControlSession.onListRecordingsForUri(ControlSession.java:148)
	at io.aeron.archive.ControlSessionDemuxer.onListRecordingsForUri(ControlSessionDemuxer.java:158)
	at io.aeron.archive.ControlRequestAdapter.onFragment(ControlRequestAdapter.java:163)
	at io.aeron.ImageFragmentAssembler.onFragment(ImageFragmentAssembler.java:109)
	at io.aeron.logbuffer.TermReader.read(TermReader.java:77)
	at io.aeron.Image.poll(Image.java:294)
	at io.aeron.archive.ControlSessionDemuxer.doWork(ControlSessionDemuxer.java:83)
	at io.aeron.archive.SessionWorker.doWork(SessionWorker.java:56)
	at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:268)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:161)
	at java.lang.Thread.run(Thread.java:748)

io.aeron.exceptions.TimeoutException: awaiting recording descriptors - correlationId=19
	at io.aeron.archive.client.AeronArchive.checkDeadline(AeronArchive.java:948)
	at io.aeron.archive.client.AeronArchive.pollForDescriptors(AeronArchive.java:1097)
	at io.aeron.archive.client.AeronArchive.listRecordingsForUri(AeronArchive.java:792)
	at io.aeron.archive.BasicArchiveTest.archiveTags(BasicArchiveTest.java:154)
```

=(

**Comment by mjpt777** [comment]
I just realised I did not push the changes for this in the last release. Master has it now.

**Comment by tmontgomery** [comment]
Others have asked for a reserved parameter that can be used as an alias to hold metadata for a URI (that Aeron won't interpret, but will preserve). Tags are a little different in that they refer to channels and subscriptions/publications (depending on usage). Subtle difference, but quite distinct, I think.

**Comment by mjpt777** [comment]
@tmontgomery The change I just pushed will support that.

**Comment by tmontgomery** [comment]
@mjpt777 indeed it will. I'll reserve "alias" as a parameter and add it to the builders, etc.

**Comment by tmontgomery** [comment]
Alias added to URI params in eef60cf31

**Comment by QIvan** [comment]
@tmontgomery cool! "Alias" sounds good. Could you describe the difference "tags" vs "aliases"?

**Comment by tmontgomery** [comment]
Tags are used to tell the driver "this subscription/publication/channel" is to use the same as this tagged channel.

Alias is a application level string attached to a channel that is not interpreted by the driver or API. An example: `aeron:udp?endpoint=localhost:45678|alias=OutboundToProcessor`

**Comment by QIvan** [comment]
hmm... if the driver doesn't interpret an alias who does?

**Comment by tmontgomery** [comment]
It's purely for the application. So, AeronStat and other tools, etc. As well as what you have been looking at, the Archive recording listings looking for channels like `alias=OutboundToProcessor` for example.

**Comment by QIvan** [comment]
ahhh i see. I just use tags as aliases right now. But in fact a human-readable word is much-much better then a number. 
Thank you very much for your explanation i'm looking forward this feature =) 

BTW may be `io.aeron.ChannelUriStringBuilder#tags(java.lang.String)` should get an `Integer` parameter instead of `String` as soon as tags are numbers only?

**Comment by tmontgomery** [comment]
Tags can be `num`, `[num,]`, and `[num,num]`. So, it would be tough.
