### ISSUE TITLE
FragmentAssemblyAdapter can't cope with an uncertain world, decides to end it all

### ISSUE THREAD

**Issue by strangelydim** [real-logic/Aeron#62]
1. Modify the RateSubscriber sample app to do fragment reassembly with the FragmentAssemblyAdapter by changing this block of code slightly:
```
        final RateReporter reporter = new RateReporter(TimeUnit.SECONDS.toNanos(1), SamplesUtil::printRate);
        final DataHandler rateReporterHandler = rateReporterHandler(reporter);

        final AtomicBoolean running = new AtomicBoolean(true);
        SigInt.register(
            () ->
            {
                reporter.halt();
                running.set(false);
            });

        try (final Aeron aeron = Aeron.connect(ctx, executor);
             final Subscription subscription = aeron.addSubscription(CHANNEL, STREAM_ID, rateReporterHandler))
```
to this:
```
        final RateReporter reporter = new RateReporter(TimeUnit.SECONDS.toNanos(1), SamplesUtil::printRate);
        final DataHandler rateReporterHandler = rateReporterHandler(reporter);
        final FragmentAssemblyAdapter dataHandler = new FragmentAssemblyAdapter(rateReporterHandler); 
        
        final AtomicBoolean running = new AtomicBoolean(true);
        SigInt.register(
            () ->
            {
                reporter.halt();
                running.set(false);
            });

        try (final Aeron aeron = Aeron.connect(ctx, executor);
             final Subscription subscription = aeron.addSubscription(CHANNEL, STREAM_ID, dataHandler))
```
2. Run the driver with large messages enabled:
```
$ java -cp aeron-samples/build/libs/samples.jar -Daeron.term.buffer.length=33554432 -Daeron.term.buffer.max.length=33554432 uk.co.real_logic.aeron.driver.MediaDriver
```
3. Run the subscriber:
```
$ java -cp aeron-samples/build/libs/samples.jar uk.co.real_logic.aeron.samples.RateSubscriber
```
4. Start the publisher sending large messages:
```
$ java -cp aeron-samples/build/libs/samples.jar -Daeron.sample.messageLength=2077151 uk.co.real_logic.aeron.sales.StreamingPublisher
```
5. Kill the subscriber, then start it again.  The second time, the subscriber will (almost always, unless you're really lucky) join in the middle of a stream of fragments and miss the beginning fragment.  Unfortunately, it is at this point that the FragmentAssemblyAdapter panics and kills itself (and the sample app) with:
```
java.lang.IllegalStateException: Begin frag not seen on session id: 139746501
	at uk.co.real_logic.aeron.FragmentAssemblyAdapter.getExistingBuilder(FragmentAssemblyAdapter.java:120)
	at uk.co.real_logic.aeron.FragmentAssemblyAdapter.onData(FragmentAssemblyAdapter.java:97)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogReader.read(LogReader.java:101)
	at uk.co.real_logic.aeron.Connection.poll(Connection.java:92)
	at uk.co.real_logic.aeron.Subscription$$Lambda$15/224070433.apply(Unknown Source)
	at uk.co.real_logic.agrona.concurrent.AtomicArray.doLimitedAction(AtomicArray.java:185)
	at uk.co.real_logic.aeron.Subscription.poll(Subscription.java:89)
	at uk.co.real_logic.aeron.samples.SamplesUtil.lambda$subscriberLoop$4(SamplesUtil.java:91)
	at uk.co.real_logic.aeron.samples.SamplesUtil$$Lambda$14/1472289531.accept(Unknown Source)
	at uk.co.real_logic.aeron.samples.RateSubscriber.lambda$main$12(RateSubscriber.java:72)
	at uk.co.real_logic.aeron.samples.RateSubscriber$$Lambda$13/1099983479.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Presumably, this might also happen if the first fragment of a fragmented message was ever simply lost on a stream even when the receiver was up the whole time.

**Comment by atarzwell** [comment]
"FragmentAssemblyAdapter can't cope with an uncertain world, decides to end it all" 

Sounds tragic.

**Comment by strangelydim** [comment]
I know - poor guy.  If only someone had been around to tell him it was all going to be okay, that he could just throw fragments away until he got a header with the Begin bit set and go from there... It didn't have to end this way.

**Comment by rlankenau** [comment]
Well, as long as he hasn't seen any previous fragments.  If he's been up the whole time, as you mentioned at the end of your initial report, he needs to do loss handling for that fragment.

Probably worth putting together a test case for that particular scenario as well.

**Comment by mjpt777** [comment]
Poor guy. I'll have to look at getting him some help... :-) Great spot.

**Comment by mjpt777** [comment]
Fixed in https://github.com/real-logic/Aeron/commit/a83b02880041d03315d37831defc233d3153a8cf
