### ISSUE TITLE
Archive gets stuck in an error loop on "response publication is closed"

### ISSUE THREAD

**Issue by ethanf** [real-logic/aeron#655]
The archive client receives a timeout:

```
io.aeron.exceptions.TimeoutException: awaiting recording descriptors - correlationId=90
        at io.aeron.archive.client.AeronArchive.checkDeadline(AeronArchive.java:1008)
        at io.aeron.archive.client.AeronArchive.pollForDescriptors(AeronArchive.java:1165)
        at io.aeron.archive.client.AeronArchive.listRecordingsForUri(AeronArchive.java:840)
        ...
```

Archive gets stuck in a loop with the error "response publication is closed"
```
121998070 observations from 2019-04-12 02:48:06.562+0000 to 2019-04-12 03:20:23.703+0000 for:
 io.aeron.archive.client.ArchiveException: response publication is closed: aeron:udp?endpoint=localhost:8020|mtu=1408|term-length=65536|sparse=true
	at io.aeron.archive.ControlResponseProxy.checkResult(ControlResponseProxy.java:149)
	at io.aeron.archive.ControlResponseProxy.sendDescriptor(ControlResponseProxy.java:72)
	at io.aeron.archive.ControlSession.sendDescriptor(ControlSession.java:302)
	at io.aeron.archive.ListRecordingsForUriSession.sendDescriptors(ListRecordingsForUriSession.java:77)
	at io.aeron.archive.AbstractListRecordingsSession.doWork(AbstractListRecordingsSession.java:66)
	at io.aeron.archive.SessionWorker.doWork(SessionWorker.java:56)
	at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:286)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mjpt777** [comment]
I've pushed a fix. Can you check if this now works for you?

**Comment by ethanf** [comment]
To repro this using v1.15.3 2ff09f502:
- Start multiple archive clients, only poll one of them. This causes backpressure on the response stream. - Do many requests until we've filled the term length. Now the archive gets back-pressure on send. 

StreamStat output:
```
     sessionId=437747255 streamId=20 channel=aeron:udp?endpoint=localhost:8020|mtu=1408|term-length=65536|sparse=true : pub-pos (sample):39:65440 pub-lmt:39:65376 snd-pos:39:32608 snd-lmt:39:32768
     sessionId=437747255 streamId=20 channel=aeron:udp?endpoint=localhost:8020 : sub-pos:11:0 sub-pos:17:0 sub-pos:23:0 sub-pos:29:0 sub-pos:35:32608 rcv-hwm:40:32608 rcv-pos:40:32608
```

Now we get the repeated error as above:

```
1711197 observations from 2019-04-15 01:15:33.257-0400 to 2019-04-15 01:15:54.297-0400 for:
 io.aeron.archive.client.ArchiveException: response publication is closed: aeron:udp?endpoint=localhost:8020|mtu=1408|term-length=65536|sparse=true
	at io.aeron.archive.ControlResponseProxy.checkResult(ControlResponseProxy.java:149)
	at io.aeron.archive.ControlResponseProxy.sendDescriptor(ControlResponseProxy.java:72)
	at io.aeron.archive.ControlSession.sendDescriptor(ControlSession.java:302)
	at io.aeron.archive.ListRecordingsForUriSession.sendDescriptors(ListRecordingsForUriSession.java:77)
	at io.aeron.archive.AbstractListRecordingsSession.doWork(AbstractListRecordingsSession.java:66)
	at io.aeron.archive.SessionWorker.doWork(SessionWorker.java:56)
	at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:286)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Doing the same after your patch using 04ecf7ffc:

```
3 observations from 2019-04-15 01:30:21.531-0400 to 2019-04-15 01:30:31.535-0400 for:
 io.aeron.archive.client.ArchiveException: unknown controlSessionId=934031932 for correlationId=598
	at io.aeron.archive.ControlSessionDemuxer.getControlSession(ControlSessionDemuxer.java:246)
	at io.aeron.archive.ControlSessionDemuxer.onListRecordingsForUri(ControlSessionDemuxer.java:157)
	at io.aeron.archive.ControlRequestAdapter.onFragment(ControlRequestAdapter.java:193)
	at io.aeron.ImageFragmentAssembler.onFragment(ImageFragmentAssembler.java:109)
	at io.aeron.logbuffer.TermReader.read(TermReader.java:75)
	at io.aeron.Image.poll(Image.java:290)
	at io.aeron.archive.ControlSessionDemuxer.doWork(ControlSessionDemuxer.java:83)
	at io.aeron.archive.SessionWorker.doWork(SessionWorker.java:58)
	at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:286)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:164)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

The archive client doesn't receive the session abort message because the response stream is back-pressured, but the archive no longer gets caught hitting the same exception repeatedly.
