### ISSUE TITLE
Not hearing from the driver for a bit is not a good reason to blow up an entire application

### ISSUE THREAD

**Issue by strangelydim** [real-logic/Aeron#69]
Currently, if you kill the driver or start up an app without the driver running... You get a runtime exception and your entire app dies:

```
uk.co.real_logic.aeron.exceptions.DriverTimeoutException: Driver has been inactive for over 10000ms
	at uk.co.real_logic.aeron.ClientConductor.checkDriverHeartbeat(ClientConductor.java:354)
	at uk.co.real_logic.aeron.ClientConductor.onKeepalive(ClientConductor.java:339)
	at uk.co.real_logic.aeron.ClientConductor$$Lambda$6/295391595.run(Unknown Source)
	at uk.co.real_logic.aeron.common.TimerWheel.expireTimers(TimerWheel.java:234)
	at uk.co.real_logic.aeron.ClientConductor.processTimers(ClientConductor.java:330)
	at uk.co.real_logic.aeron.ClientConductor.doWork(ClientConductor.java:106)
	at uk.co.real_logic.aeron.common.AgentRunner.run(AgentRunner.java:85)
	at java.lang.Thread.run(Thread.java:745)
uk.co.real_logic.aeron.exceptions.DriverTimeoutException: Driver has been inactive for over 10000ms
	at uk.co.real_logic.aeron.ClientConductor.checkDriverHeartbeat(ClientConductor.java:354)
	at uk.co.real_logic.aeron.ClientConductor.onKeepalive(ClientConductor.java:339)
	at uk.co.real_logic.aeron.ClientConductor$$Lambda$6/295391595.run(Unknown Source)
	at uk.co.real_logic.aeron.common.TimerWheel.expireTimers(TimerWheel.java:234)
	at uk.co.real_logic.aeron.ClientConductor.processTimers(ClientConductor.java:330)
	at uk.co.real_logic.aeron.ClientConductor.doWork(ClientConductor.java:106)
	at uk.co.real_logic.aeron.common.AgentRunner.run(AgentRunner.java:85)
	at java.lang.Thread.run(Thread.java:745)

***
*** Timeout from the Media Driver - is it currently running? Exiting.
***
uk.co.real_logic.aeron.exceptions.DriverTimeoutException: Driver has been inactive for over 10000ms
	at uk.co.real_logic.aeron.ClientConductor.checkDriverHeartbeat(ClientConductor.java:354)
	at uk.co.real_logic.aeron.ClientConductor.onKeepalive(ClientConductor.java:339)
	at uk.co.real_logic.aeron.ClientConductor$$Lambda$6/295391595.run(Unknown Source)
	at uk.co.real_logic.aeron.common.TimerWheel.expireTimers(TimerWheel.java:234)
	at uk.co.real_logic.aeron.ClientConductor.processTimers(ClientConductor.java:330)
	at uk.co.real_logic.aeron.ClientConductor.doWork(ClientConductor.java:106)
```

That seems a little harsh.  Maybe the app wanted to do other things and live a long and fulfilling life after the driver died.  Maybe he wanted to tell someone else the driver was down and to please restart it manually for him, etc., so he could try connecting again.  But he never got the chance.

Maybe turn the exception into a log message instead?  Maybe turn it into a user-visible event type/callback?  Something other than blowing up the entire app, in any case.

**Comment by mjpt777** [comment]
"Blow up the application" now that is a little harsh. Well if you don't handle your exceptions correctly ;-)

Seriously though we do need to think what is the correct strategy. I put this in place so it is not forgotten about. A log entry feels too soft. Some sensible middle ground is required.

**Comment by rlankenau** [comment]
I agree that a log entry feels too soft, and if you're going to handle it programmatically, requires parsing.  Some sort of context-level callback is easier to encapsulate for a user.

I'm assuming that the exception is thrown from a thread started by the Aeron context, so catching it at the application level would be a bit of a trick.

**Comment by strangelydim** [comment]
Maybe allow the user to hook up their own custom error log callback when they create the Aeron context?

**Comment by rlankenau** [comment]
If there's a severity included in the callback, that could work.  If we expect that the media driver going away is a common transient condition that the client is going to be able to recover from, I'd think that a log message with a low severity would be okay, maybe escalating the severity after some threshold.

I prefer a more strongly typed notification for severe and well-defined system events, but I recognize that those can rapidly bloat the application code for handling events.

**Comment by mjpt777** [comment]
Currently it passes a `DriverTimeoutException` to the provided default error handler in the client context. The default error handler prints out an error and exits the client.

You can prove your own `Aeron.Context.errorHandler(final Consumer<Throwable> handler)` and decide what to do.

**Comment by rlankenau** [comment]
Ah, well, that actually seems just fine to me.

**Comment by strangelydim** [comment]
Ah, whoops. I just missed context.errorHandler(). So not really a bug - although maybe either: 1. specifying an errorHandler should be mandatory or 2. the default error handler should just log a message but not exit.

Otherwise, I'm worried that someone might write an app and test it (not very thoroughly), _thinking_ that all is well, until the first time they get a context error and their app unexpectedly quits on them.
