### ISSUE TITLE
Default TO_CLIENTS_BUFFER_LENGTH_DEFAULT incorrect

### ISSUE THREAD

**Issue by phaynes** [real-logic/Aeron#84]
In the file: uk.co.real_logic.aeron.driver.Configuration line: 173  
the parameter TO_CLIENTS_BUFFER_LENGTH_DEFAULT is being set to 1,048,704 (two cache lines) rather than 1048640. 2^20+64 (I could figure out why). 

This is causing the media driver to fail start up and everything to stop working.

Running applications with -Daeron.clients.buffer.length=1048640 acts as a workaround to the issue.

**Comment by mjpt777** [comment]
What was the startup error you are seeing? I'm not seeing that.

The two cache lines was for the trailer that contains the counters. In the last Agrona I've reduced this to one cache line but that is not pushed to Maven Central yet.

**Comment by phaynes** [comment]
I breath a sign of relief.

The full error is per below.

I was pulling from the Agrona snapshot release rather than 0.3 maven central version. 
I have adjusted the build to use the 0.3 Agrona rather than the snap shot release and the problems disappears.

java -Daeron.mtu.length=16384 -Daeron.socket.so_sndbuf=16384 -Daeron.socket.so_rcvbuf=2097152 -Daeron.rcv.buffer.length=16384 -Daeron.rcv.initial.window.length=2097152 -Dagrona.disable.bounds.checks=true -jar mediadriver-0.0.2-SNAPSHOT-jar-with-dependencies.jar 
Exception in thread "main" java.lang.IllegalStateException: Capacity must be a positive power of 2 + TRAILER_LENGTH: capacity=1048640
	at uk.co.real_logic.agrona.concurrent.broadcast.BroadcastBufferDescriptor.checkCapacity(BroadcastBufferDescriptor.java:63)
	at uk.co.real_logic.agrona.concurrent.broadcast.BroadcastTransmitter.<init>(BroadcastTransmitter.java:55)
	at uk.co.real_logic.aeron.driver.MediaDriver$Context.conclude(MediaDriver.java:342)
	at uk.co.real_logic.aeron.driver.MediaDriver.<init>(MediaDriver.java:105)
	at uk.co.real_logic.aeron.driver.MediaDriver.launch(MediaDriver.java:164)
	at com.threatmetrix.cm.CMMediaDriver.main(CMMediaDriver.java:22)

**Comment by mjpt777** [comment]
No worries :-)
