### ISSUE TITLE
segfault in aeronmd (aeron_counter_set_ordered)

### ISSUE THREAD

**Issue by srosenberg** [real-logic/aeron#955]
There seems to be a race condition in `aeron_counter_set_ordered` when executing on `i9-9900k` processor.  Below is a minimal program for reproduction,

```
#include "Aeron.h"
int main() {
    aeron::Context context;
    std::shared_ptr<aeron::Aeron> aeron = aeron::Aeron::connect(context);
    aeron->addSubscription("aeron:udp?endpoint=8.8.8.8:8888", 1);
}
```

resulting in the follow stack trace,

```
------------------ gdb trace of aeronmd: -------------------------------
Starting program: binaries/aeronmd 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff72b2700 (LWP 225572)]
[New Thread 0x7ffff6ab1700 (LWP 225573)]
Thread 1 "aeronmd" received signal SIGSEGV, Segmentation fault.
0x00007ffff7f648f0 in aeron_counter_set_ordered (addr=0x0, value=2)
    at aeron/aeron-client/src/main/c/concurrent/aeron_counters_manager.h:235
235         AERON_PUT_ORDERED(*addr, value);
(gdb) info stack
#0  0x00007ffff7f648f0 in aeron_counter_set_ordered (addr=0x0, value=2)
    at aeron-client/src/main/c/concurrent/aeron_counters_manager.h:235
#1  0x00007ffff7f8212d in aeron_receive_destination_delete (destination=0x55555557f960, counters_manager=0x55555555c8d0)
    at aeron/aeron-driver/src/main/c/media/aeron_receive_destination.c:111
#2  0x00007ffff7f81edc in aeron_receive_destination_create (destination=0x7fffffffcee8, channel=0x55555557f180, 
    context=0x55555555a2a0, counters_manager=0x55555555c8d0, channel_status_counter_id=27)
    at aeron/aeron-driver/src/main/c/media/aeron_receive_destination.c:53
#3  0x00007ffff7f9172a in aeron_driver_conductor_get_or_add_receive_channel_endpoint (conductor=0x55555555c828, 
    channel=0x55555557f180) at aeron/aeron-driver/src/main/c/aeron_driver_conductor.c:1405
#4  0x00007ffff7f94b7b in aeron_driver_conductor_on_add_network_subscription (conductor=0x55555555c828, command=0x7ffff73b3088)
    at aeron/aeron-driver/src/main/c/aeron_driver_conductor.c:2595
#5  0x00007ffff7f92314 in aeron_driver_conductor_on_command (msg_type_id=4, message=0x7ffff73b3088, length=63, 
    clientd=0x55555555c828) at aeron/aeron-driver/src/main/c/aeron_driver_conductor.c:1705
#6  0x00007ffff7f67660 in aeron_mpsc_rb_read (ring_buffer=0x55555555c830, 
    handler=0x7ffff7f91f3c <aeron_driver_conductor_on_command>, clientd=0x55555555c828, message_count_limit=10)
    at aeron/aeron-client/src/main/c/concurrent/aeron_mpsc_rb.c:183
#7  0x00007ffff7f92a78 in aeron_driver_conductor_do_work (clientd=0x55555555c828)
    at aeron/aeron-driver/src/main/c/aeron_driver_conductor.c:1931
#8  0x00007ffff7f6ee3d in aeron_agent_do_work (runner=0x55555555d0b0)
    at aeron/aeron-client/src/main/c/aeron_agent.h:105
#9  0x00007ffff7f8d034 in aeron_driver_main_do_work (driver=0x55555555c820)
    at aeron/aeron-driver/src/main/c/aeron_driver.c:978
#10 0x00005555555568b4 in main (argc=1, argv=0x7fffffffdfd8) at aeron/aeron-driver/src/main/c/aeronmd.c:135
```

Note, the above program exits with `0` while `aeronmd` crashes due to segfault.

The above is reproducible against ` v1.28.1` and ` v1.28.2` (release tags) running on `i9-9900k` processor under `ubuntu 20.04`.  This appears to be _specific_ to `i9-9900k` as we're unable to reproduce using a different CPU.

**Comment by mjpt777** [comment]
@srosenberg Did you recreate this with head?

**Comment by srosenberg** [comment]
No longer reproducible on our side with the latest head. Thanks! Closing.
