### ISSUE TITLE
IndexOutOfBoundsException on PublisherTool upon restart

### ISSUE THREAD

**Issue by strangelydim** [real-logic/Aeron#96]
If I start SubscriberTool (with an embedded driver, embedded vs. not probably doesn't matter here):

```
$ java -cp aeron-tools/build/libs/tools.jar uk.co.real_logic.aeron.tools.SubscriberTool --driver=embedded
```

and then start PublisherTool:

```
$ java -cp aeron-tools/build/libs/tools.jar uk.co.real_logic.aeron.tools.PublisherTool
```

All is well.  However, if I then kill PublisherTool and restart it right away (sometimes it takes a handful of kills/restarts), then it'll often fail with this:

```
java.lang.IndexOutOfBoundsException: index=16777208, length=24, capacity=16777216
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:795)
	at uk.co.real_logic.agrona.concurrent.UnsafeBuffer.putBytes(UnsafeBuffer.java:724)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendPaddingFrame(LogAppender.java:304)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.appendUnfragmentedMessage(LogAppender.java:216)
	at uk.co.real_logic.aeron.common.concurrent.logbuffer.LogAppender.append(LogAppender.java:142)
	at uk.co.real_logic.aeron.Publication.offer(Publication.java:192)
	at uk.co.real_logic.aeron.tools.PublisherTool$PublisherThread.onNext(PublisherTool.java:433)
	at uk.co.real_logic.aeron.tools.RateController$SecondsAtBitsPerSecondInternal.sendNext(RateController.java:495)
	at uk.co.real_logic.aeron.tools.RateController.next(RateController.java:63)
	at uk.co.real_logic.aeron.tools.PublisherTool$PublisherThread.run(PublisherTool.java:372)
	at java.lang.Thread.run(Thread.java:745)
```

Note that PublisherTool, with all default options, will be using the exact same channel, stream ID, _and session ID_ each time it starts up.  (Always udp://localhost:31111#1[1]).

**Comment by tmontgomery** [comment]
Currently, this is not supported. The setting of sessionId brings with it some responsibility. One thing is to allow previous invocations to time out on the receivers.

We may address this later, though.

**Comment by tmontgomery** [comment]
Just to be aware. Setting the sessionId is advanced usage and will take with it some responsibility. To that end, we probably need to make it easier for the user in some way.

**Comment by strangelydim** [comment]
Yep, correct. There's just one media driver, and it stays up the whole time.

**Comment by tmontgomery** [comment]
Would you be so kind as to retest this with the latest changes?

**Comment by tmontgomery** [comment]
Have not seen a retest on this since the client threading model was redone. Let us know if this still persists.
